// Pages and quick actions offered by the ⌘K command palette, per workspace.
// The palette only shows entries for workspaces the signed-in role can open.
import type { Workspace } from "@/lib/access";

export interface Command { label: string; href: string; keywords?: string; kind: "page" | "action"; audience?: "AGENT" | "STAFF" }

const page = (label: string, href: string, keywords = ""): Command => ({ label, href, keywords, kind: "page" });
const action = (label: string, href: string, keywords = ""): Command => ({ label, href, keywords, kind: "action" });

export const COMMANDS: Record<Workspace, Command[]> = {
    ADMIN: [
        action("Create task", "/admin/tasks?create=1", "new todo ticket assign"),
        action("Post announcement", "/admin/announcements", "notice broadcast"),
        page("Admin overview", "/admin/dashboard", "home kpi"),
        page("Jobs", "/admin/jobs", "requisitions positions openings"),
        page("Candidates", "/admin/candidates", "talent pool profiles"),
        page("Interviews", "/admin/interviews", "schedule rounds"),
        page("Placements", "/admin/placements", "joined hires"),
        page("Tasks & follow-ups", "/admin/tasks", "todo board"),
        page("Clients", "/admin/clients", "accounts companies"),
        page("Client leads", "/admin/client-leads", "prospects sales"),
        page("Team", "/admin/team", "users recruiters staff"),
        page("Performance", "/admin/performance", "recruiter leaderboard"),
        page("Reports", "/admin/reports", "analytics"),
        page("Approvals", "/admin/approvals", "pending sign off"),
        page("Compliance", "/admin/compliance", "dpdp consent statutory"),
        page("Audit log", "/admin/audit-log", "history changes"),
        page("Integrations", "/admin/integrations", "connect apps"),
        page("Settings", "/admin/settings", "configuration database"),
    ],
    TA: [
        action("Create task", "/ta/tasks?create=1", "new todo ticket follow up"),
        action("Add candidate", "/ta/candidates", "new profile resume upload"),
        action("Raise requisition", "/ta/requisitions", "new job opening"),
        page("TA overview", "/ta/dashboard", "home"),
        page("Requisitions", "/ta/requisitions", "jobs openings"),
        page("Pipeline", "/ta/pipeline", "kanban stages board"),
        page("Candidates", "/ta/candidates", "talent"),
        page("Interviews", "/ta/interviews", "schedule feedback"),
        page("Offers & joinings", "/ta/joinings", "offer letter onboarding"),
        page("Referrals", "/ta/referrals", "agent partner"),
        page("Recruitment tasks", "/ta/tasks", "todo board"),
        page("My clients", "/ta/clients", "accounts"),
        page("Message templates", "/ta/templates", "email whatsapp"),
        page("Partners", "/ta/partners", "agents kyc"),
        page("My performance", "/ta/performance", "targets"),
        page("Recruitment reports", "/ta/reports", "analytics"),
    ],
    HR: [
        action("Create task", "/hr/tasks?create=1", "new todo ticket"),
        action("Add employee", "/hr/employees", "new hire staff"),
        page("HR command center", "/hr/dashboard", "home"),
        page("Employees", "/hr/employees", "staff directory"),
        page("Onboarding", "/hr/onboarding", "joining checklist"),
        page("Attendance", "/hr/attendance", "check in late"),
        page("Leave requests", "/hr/leave", "time off approve"),
        page("Holidays", "/hr/holidays", "calendar"),
        page("Payroll", "/hr/payroll", "salary run payslips"),
        page("Performance", "/hr/performance", "appraisal goals okr"),
        page("Lifecycle", "/hr/lifecycle", "promotion transfer probation"),
        page("Exit management", "/hr/exit", "resignation fnf"),
        page("Documents", "/hr/documents", "letters files"),
        page("Assets", "/hr/assets", "laptop equipment"),
        page("Training", "/hr/training", "learning courses"),
        page("Benefits", "/hr/benefits", "insurance"),
        page("Tax declarations", "/hr/tax-declarations", "80c investment"),
        page("HR approvals", "/hr/approvals", "pending"),
        page("HR reports", "/hr/reports", "analytics export csv"),
        page("HR tasks", "/hr/tasks", "todo board"),
    ],
    FINANCE: [
        action("Create invoice", "/finance/invoices", "bill client gst"),
        action("Record receipt", "/finance/receipts", "payment received"),
        page("Finance overview", "/finance/dashboard", "home cash"),
        page("Billing queue", "/finance/billing", "ready to bill placements"),
        page("Invoices", "/finance/invoices", "receivables"),
        page("Receipts", "/finance/receipts", "collections"),
        page("Recurring billing", "/finance/recurring", "retainer"),
        page("Contracts & timesheets", "/finance/contracts", "contractors"),
        page("Payroll (finance)", "/finance/payroll", "disburse salary"),
        page("Vendors & bills", "/finance/vendors", "payables"),
        page("Incentives & payouts", "/finance/payables", "commission agents"),
        page("Expenses", "/finance/expenses", "claims reimbursement"),
        page("Books & ledger", "/finance/accounting", "journal trial balance"),
        page("Bank reconciliation", "/finance/bank", "statement match"),
        page("GST & TDS", "/finance/tax", "returns"),
        page("Finance reports", "/finance/reports", "p&l budget"),
        page("Finance settings", "/finance/settings", "gst bank"),
    ],
    PORTAL: [
        { ...action("Apply for leave", "/portal/leave", "time off holiday sick casual"), audience: "STAFF" },
        { ...action("Mark attendance", "/portal/attendance", "check in check out punch"), audience: "STAFF" },
        action("Refer a candidate", "/portal/referrals", "earn referral bonus"),
        { ...action("Raise a request", "/portal/requests", "letter certificate it support"), audience: "STAFF" },
        action("Create task", "/portal/tasks?create=1", "new todo"),
        page("My dashboard", "/portal/dashboard", "home"),
        page("My profile", "/portal/profile", "personal details bank"),
        page("My tasks", "/portal/tasks", "todo"),
        { ...page("Payslips & salary", "/portal/payslips", "salary slip"), audience: "STAFF" },
        { ...page("Tax & Form 16", "/portal/tax", "tds"), audience: "STAFF" },
        { ...page("Expenses", "/portal/expenses", "claim reimbursement"), audience: "STAFF" },
        { ...page("Holidays", "/portal/holidays", "calendar"), audience: "STAFF" },
        { ...page("Announcements", "/portal/announcements", "news"), audience: "STAFF" },
        { ...page("Policies", "/portal/policies", "handbook"), audience: "STAFF" },
        { ...page("People directory", "/portal/directory", "colleagues contacts"), audience: "STAFF" },
        page("Open jobs", "/portal/jobs", "openings refer"),
        { ...page("My earnings", "/portal/incentives", "payout commission"), audience: "AGENT" },
        { ...page("Performance & goals", "/portal/performance", "okr appraisal"), audience: "STAFF" },
        { ...page("Training", "/portal/training", "courses"), audience: "STAFF" },
    ],
};
