-- ════════════════════════════════════════════════════════════
-- Setup — schema
-- All CRM tables live in their own "crm" schema so they never collide with the website's tables in "public".
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

create schema if not exists crm;
comment on schema crm is 'AbsoJob CRM (admin, HR, TA, finance and employee portal). Accessed server-side only.';
