-- ════════════════════════════════════════════════════════════
-- Core — organizations, logins, settings
-- Tenants, every staff/partner login, and per-org settings blobs.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- One row per tenant (staffing agency).
create table if not exists crm.organizations (
  id           text not null,
  name         text,
  slug         text,
  plan         text, -- TRIAL | STARTER | GROWTH | ENTERPRISE
  status       text, -- ACTIVE | SUSPENDED
  industry     text,
  logo_url     text,
  created_at   timestamptz,
  _extra       jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position    double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Every login: admins, HR, finance, TA, field agents, employees. password_hash is NULL for seeded demo users (they use the demo password).
create table if not exists crm.users (
  id                    text not null,
  org_id                text not null,
  name                  text,
  email                 text,
  phone                 text,
  role                  text, -- SUPER_ADMIN | TA_MANAGER | TA_RECRUITER | AGENT | EMPLOYEE | HR_ADMIN | FINANCE_ADMIN
  status                text, -- ACTIVE | SUSPENDED | INVITED | EXITED
  avatar_url            text,
  department            text,
  designation           text,
  location              text,
  reporting_to          text,
  joined_at             timestamptz,
  deactivated_at        timestamptz,
  password_hash         text,
  password_changed_at   timestamptz,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Agency profile and preferences, one JSON document per organization.
create table if not exists crm.organization_settings (
  org_id      text not null,
  settings    jsonb not null,
  _extra      jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position   double precision not null default 0, -- list order the app expects
  primary key (org_id)
);
