-- ════════════════════════════════════════════════════════════
-- Recruitment — clients, jobs, candidates, pipeline
-- The TA workspace: client accounts, requisitions, the candidate bank, applications moving through stages, interviews and placements.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- Backs the "clients" collection (type Client).
create table if not exists crm.clients (
  id                   text not null,
  org_id               text not null,
  company_name         text,
  industry             text,
  website              text,
  contact_person       text,
  contact_email        text,
  contact_phone        text,
  address              text,
  status               text, -- ACTIVE | PROSPECT | ONBOARDING | PAUSED | CHURNED
  agreement_url        text,
  commission_rate      numeric,
  credit_days          numeric,
  account_manager_id   text,
  estimated_value      text,
  notes                text,
  billing              jsonb,
  credit_hold          boolean,
  created_at           timestamptz,
  updated_at           timestamptz,
  _extra               jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position            double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "clientLeads" collection (type ClientLead).
create table if not exists crm.client_leads (
  id                          text not null,
  org_id                      text not null,
  company_name                text,
  contact_person              text,
  email                       text,
  phone                       text,
  industry                    text,
  location                    text,
  lead_source                 text, -- OUTBOUND | INBOUND_WEB | LINKEDIN | REFERRAL | EVENT
  assigned_to_name            text,
  assigned_to_id              text,
  stage                       text, -- NEW | CONTACTED | QUALIFIED | MEETING | PROPOSAL | NEGOTIATION | CONVERTED | LOST
  expected_positions          numeric,
  expected_annual_value_lpa   numeric,
  priority                    text, -- LOW | MEDIUM | HIGH | URGENT
  next_follow_up_date         text,
  notes                       text,
  converted_client_id         text,
  created_at                  timestamptz,
  updated_at                  timestamptz,
  _extra                      jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                   double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "clientCommunications" collection (type ClientCommunication).
create table if not exists crm.client_communications (
  id                    text not null,
  org_id                text not null,
  client_id             text,
  channel               text, -- MEETING | EMAIL | PHONE | WHATSAPP
  direction             text, -- INCOMING | OUTGOING
  subject               text,
  body                  text,
  job_id                text,
  next_follow_up_date   date,
  by_user_id            text,
  by_name               text,
  created_at            timestamptz,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "jobs" collection (type JobRequisition).
create table if not exists crm.jobs (
  id                         text not null,
  org_id                     text not null,
  client_id                  text,
  title                      text,
  department                 text,
  location                   text,
  work_mode                  text, -- ONSITE | HYBRID | REMOTE | FIELD
  city                       text,
  country                    text,
  employment_type            text, -- HYBRID | REMOTE | FULL_TIME | PART_TIME | CONTRACT | TEMPORARY | INTERNSHIP | CONSULTANT
  priority                   text, -- LOW | MEDIUM | HIGH | URGENT
  priority_reason            text,
  openings                   numeric,
  filled                     numeric,
  salary_min_lpa             numeric,
  salary_max_lpa             numeric,
  salary_currency            text,
  fixed_salary_lpa           numeric,
  variable_salary_lpa        numeric,
  bonus_details              text,
  benefits                   text,
  experience_min_years       numeric,
  experience_max_years       numeric,
  skills                     text[],
  preferred_skills           text[],
  education                  text,
  certifications             text[],
  languages                  text[],
  notice_period_preference   text,
  description                text,
  about_company              text,
  responsibilities           text,
  status                     text, -- DRAFT | PENDING_APPROVAL | APPROVED | SOURCING | SCREENING | CLIENT_REVIEW | INTERVIEWING | OFFER_STAGE | JOINING | FULFILLED | ON_HOLD | CLOSED | CANCELLED
  status_reason              text,
  hold_resume_date           date,
  closure_reason             text,
  cancel_reason              text,
  requested_by_id            text,
  approved_by_id             text,
  assigned_tas               text[],
  primary_recruiter_id       text,
  ta_manager_id              text,
  account_manager_id         text,
  target_close_date          text,
  target_joining_date        text,
  sla_days                   numeric,
  sla                        jsonb,
  tags                       text[],
  openings_list              jsonb,
  requirement_versions       jsonb,
  assignment_history         jsonb,
  documents                  jsonb,
  approvals                  jsonb,
  created_at                 timestamptz,
  updated_at                 timestamptz,
  _extra                     jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                  double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "candidates" collection (type Candidate).
create table if not exists crm.candidates (
  id                          text not null,
  org_id                      text not null,
  candidate_code              text,
  name                        text,
  email                       text,
  alternate_email             text,
  phone                       text,
  alternate_phone             text,
  whatsapp_number             text,
  gender                      text, -- Male | Female | Non-Binary | Prefer not to say
  date_of_birth               date,
  nationality                 text,
  marital_status              text,
  current_city                text,
  current_state               text,
  current_country             text,
  permanent_address           text,
  pin_code                    text,
  bio                         text,
  headline                    text,
  current_company             text,
  current_designation         text,
  previous_company            text,
  total_experience_years      numeric,
  relevant_experience_years   numeric,
  industry                    text,
  functional_area             text,
  employment_type             text,
  seniority_level             text, -- Junior | Mid-Level | Senior | Lead | Staff | Principal | Executive
  current_ctc_lpa             numeric,
  expected_ctc_lpa            numeric,
  notice_period_days          numeric,
  location                    text,
  status                      text, -- ACTIVE | NEW | CONTACTED | QUALIFIED | ON_HOLD | AVAILABLE | PLACED | JOINED | REJECTED | BLACKLISTED | ARCHIVED
  tags                        text[],
  skills                      text[],
  primary_skills              text[],
  secondary_skills            text[],
  detailed_skills             jsonb,
  certifications              text[],
  education                   jsonb,
  work_experience             jsonb,
  preferences                 jsonb,
  compensation_details        jsonb,
  availability_details        jsonb,
  documents                   jsonb,
  communications              jsonb,
  notes                       jsonb,
  screening_evaluation        jsonb,
  reference_checks            jsonb,
  compliance                  jsonb,
  ownership                   jsonb,
  resume_url                  text,
  portfolio_url               text,
  linkedin_url                text,
  github_url                  text,
  website_url                 text,
  rating                      numeric,
  profile_completion_score    numeric,
  source                      text, -- LINKEDIN | AGENT_REFERRAL | JOB_PORTAL | WALK_IN | DATABASE | CAMPUS | OTHER
  source_campaign             text,
  referred_by_user_id         text,
  blacklisted                 boolean,
  blacklist_reason            text,
  do_not_contact              boolean,
  do_not_contact_reason       text,
  archived                    boolean,
  offers                      jsonb,
  client_submissions          jsonb,
  candidate_tasks             jsonb,
  internal_audit_logs         jsonb,
  custom_field_values         jsonb,
  created_at                  timestamptz,
  updated_at                  timestamptz,
  _extra                      jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                   double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "applications" collection (type Application).
create table if not exists crm.applications (
  id                   text not null,
  org_id               text not null,
  candidate_id         text,
  job_id               text,
  stage                text, -- ONBOARDING | SCREENING | ON_HOLD | JOINED | REJECTED | BLACKLISTED | SOURCED | INTERVIEW_SCHEDULED | TECH_ROUND | CLIENT_ROUND | HR_ROUND | OFFER_SENT | OFFER_ACCEPTED | BACKED_OUT
  recruiter_id         text,
  fit_score            numeric,
  screening_notes      text,
  rejection_reason     text,
  hold_reason          text,
  stage_before_hold    text, -- ONBOARDING | SCREENING | ON_HOLD | JOINED | REJECTED | BLACKLISTED | SOURCED | INTERVIEW_SCHEDULED | TECH_ROUND | CLIENT_ROUND | HR_ROUND | OFFER_SENT | OFFER_ACCEPTED | BACKED_OUT
  expected_join_date   date,
  actual_join_date     date,
  created_at           timestamptz,
  updated_at           timestamptz,
  _extra               jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position            double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "interviews" collection (type Interview).
create table if not exists crm.interviews (
  id                    text not null,
  org_id                text not null,
  application_id        text,
  round                 text, -- CLIENT_ROUND | HR_ROUND | SCREENING_CALL | TECH_1 | TECH_2 | FINAL
  mode                  text, -- PHONE | ONSITE | VIDEO
  scheduled_at          timestamptz,
  duration_mins         numeric,
  interviewer_name      text,
  interviewer_user_id   text,
  status                text, -- CANCELLED | SCHEDULED | COMPLETED | NO_SHOW | RESCHEDULED
  outcome               text, -- PENDING | STRONG_HIRE | HIRE | MAYBE | NO_HIRE
  score                 numeric,
  feedback              text,
  meeting_link          text,
  created_by            text,
  created_at            timestamptz,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "placements" collection (type PlacementRecord).
create table if not exists crm.placements (
  id                      text not null,
  org_id                  text not null,
  candidate_id            text,
  candidate_name          text,
  client_id               text,
  client_name             text,
  job_id                  text,
  job_title               text,
  recruiter_id            text,
  recruiter_name          text,
  account_manager_name    text,
  placement_date          text,
  offered_position        text,
  offered_salary_lpa      numeric,
  joining_date            text,
  joining_status          text, -- CANCELLED | JOINED | NO_SHOW | JOINING_PENDING | DEFERRED
  revenue_inr             numeric,
  invoice_id              text,
  invoice_number          text,
  guarantee_period_days   numeric,
  guarantee_end_date      text,
  replacement_status      text, -- CLOSED | NO_REPLACEMENT | REPLACEMENT_REQUESTED | REPLACEMENT_IN_PROGRESS | REPLACEMENT_COMPLETED
  notes                   text,
  created_at              timestamptz,
  _extra                  jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position               double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "messageTemplates" collection (type MessageTemplate).
create table if not exists crm.message_templates (
  id                text not null,
  org_id            text not null,
  name              text,
  channel           text, -- EMAIL | WHATSAPP | SMS
  audience          text, -- CANDIDATE | CLIENT
  subject           text,
  body              text,
  created_by_name   text,
  created_at        timestamptz,
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "recruiterTargets" collection (type RecruiterTarget).
create table if not exists crm.recruiter_targets (
  id            text not null,
  org_id        text not null,
  user_id       text,
  month         text,
  submissions   numeric,
  interviews    numeric,
  offers        numeric,
  joinings      numeric,
  revenue       numeric,
  set_by_name   text,
  _extra        jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position     double precision not null default 0, -- list order the app expects
  primary key (id)
);
