-- ════════════════════════════════════════════════════════════
-- Partners — field agents, referrals, commissions
-- External talent partners (AGENT role): their KYC profile, referrals they submit, the referral chat thread, commission ledger and payouts.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- Backs the "agentProfiles" collection (type AgentProfile).
create table if not exists crm.agent_profiles (
  user_id                 text not null,
  org_id                  text not null,
  city                    text,
  pan                     text,
  id_proof_file_id        text,
  kyc_status              text, -- REJECTED | PENDING | VERIFIED
  kyc_note                text,
  specialization          text[],
  experience_years        numeric,
  sourcing_channels       text[],
  agreement_accepted_at   timestamptz,
  verified_by_name        text,
  verified_at             timestamptz,
  created_at              timestamptz,
  _extra                  jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position               double precision not null default 0, -- list order the app expects
  primary key (user_id)
);

-- Backs the "referrals" collection (type Referral).
create table if not exists crm.referrals (
  id                  text not null,
  org_id              text not null,
  agent_id            text,
  candidate_id        text,
  job_id              text,
  status              text, -- REJECTED | SUBMITTED | UNDER_REVIEW | SHORTLISTED | HIRED
  incentive_amount    numeric,
  incentive_paid      boolean,
  review_notes        text,
  resume_file_id      text,
  candidate_consent   boolean,
  agent_notes         text,
  created_at          timestamptz,
  updated_at          timestamptz,
  _extra              jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position           double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "referralMessages" collection (type ReferralMessage).
create table if not exists crm.referral_messages (
  id             text not null,
  org_id         text not null,
  referral_id    text,
  from_user_id   text,
  from_name      text,
  from_role      text, -- SUPER_ADMIN | TA_MANAGER | TA_RECRUITER | AGENT | EMPLOYEE | HR_ADMIN | FINANCE_ADMIN
  text           text,
  created_at     timestamptz,
  _extra         jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position      double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "commissionLedger" collection (type CommissionLedgerEntry).
create table if not exists crm.commission_ledger (
  id               text not null,
  org_id           text not null,
  user_id          text,
  client_id        text,
  application_id   text,
  type             text, -- PLACEMENT_COMMISSION | REFERRAL_INCENTIVE | RECRUITER_INCENTIVE | CLAWBACK | PAYOUT | ADJUSTMENT
  amount_inr       numeric,
  status           text, -- APPROVED | CANCELLED | PENDING | PAID
  description      text,
  invoice_number   text,
  due_date         date,
  paid_at          timestamptz,
  tds_amount       numeric,
  placement_id     text,
  created_at       timestamptz,
  _extra           jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position        double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "payouts" collection (type Payout).
create table if not exists crm.payouts (
  id             text not null,
  org_id         text not null,
  user_id        text,
  amount_inr     numeric,
  period_label   text,
  status         text, -- ON_HOLD | PAID | PROCESSING
  method         text, -- BANK_TRANSFER | UPI | CHEQUE
  reference      text,
  processed_at   timestamptz,
  created_at     timestamptz,
  _extra         jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position      double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "payeeProfiles" collection (type PayeeProfile).
create table if not exists crm.payee_profiles (
  user_id               text not null,
  pan                   text,
  bank_name             text,
  bank_account_number   text,
  bank_ifsc             text,
  upi_id                text,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (user_id)
);
