-- ════════════════════════════════════════════════════════════
-- HR — employee records and lifecycle
-- The HR record behind every staff login, plus onboarding, documents, assets, probation, promotions, transfers, salary revisions and exits.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- HR record behind each staff login (agents excluded). employee_id is the human code, e.g. EMP-001.
create table if not exists crm.employees (
  id                       text not null,
  org_id                   text not null,
  employee_id              text,
  user_id                  text,
  candidate_id             text,
  name                     text,
  email                    text,
  phone                    text,
  department               text,
  designation              text,
  reporting_manager_id     text,
  reporting_manager_name   text,
  joining_date             date,
  employment_type          text, -- FULL_TIME | PART_TIME | CONTRACT | INTERN
  status                   text, -- ACTIVE | EXITED | ON_LEAVE | NOTICE_PERIOD
  gender                   text, -- OTHER | MALE | FEMALE | PREFER_NOT_TO_SAY
  location                 text,
  personal_details         jsonb,
  bank_details             jsonb,
  emergency_contact        jsonb,
  salary                   jsonb,
  probation_end_date       date,
  probation_status         text, -- ON_PROBATION | CONFIRMED | EXTENDED
  contract_end_date        date,
  avatar_url               text,
  work_mode                text, -- HYBRID | REMOTE | OFFICE
  shift_id                 text,
  personal_email           text,
  created_at               timestamptz,
  updated_at               timestamptz,
  _extra                   jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "onboardingRecords" collection (type OnboardingRecord).
create table if not exists crm.onboarding_records (
  id                      text not null,
  org_id                  text not null,
  candidate_id            text,
  application_id          text,
  job_id                  text,
  candidate_name          text,
  candidate_email         text,
  candidate_phone         text,
  position                text,
  department              text,
  expected_joining_date   date,
  actual_joining_date     date,
  status                  text, -- REJECTED | COMPLETED | PENDING | IN_PROGRESS
  progress_percent        numeric,
  checklist               jsonb,
  assigned_hr_id          text,
  created_employee_id     text,
  notes                   text,
  created_at              timestamptz,
  updated_at              timestamptz,
  _extra                  jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position               double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "documents" collection (type DocumentRecord).
create table if not exists crm.employee_documents (
  id                 text not null,
  org_id             text not null,
  employee_id        text,
  employee_name      text,
  title              text,
  category           text, -- IDENTITY | ADDRESS | OFFER_LETTER | APPOINTMENT_LETTER | EXPERIENCE_LETTER | SALARY_CERTIFICATE | BANK_DOC | EMPLOYMENT | RESUME | POLICY
  file_url           text,
  file_size          text,
  status             text, -- REJECTED | PENDING | VERIFIED
  expiry_date        date,
  uploaded_at        timestamptz,
  uploaded_by_name   text,
  reviewed_by_name   text,
  rejection_reason   text,
  version            numeric,
  _extra             jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position          double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "assets" collection (type AssetRecord).
create table if not exists crm.employee_assets (
  id                       text not null,
  org_id                   text not null,
  asset_tag                text,
  name                     text,
  category                 text, -- OTHER | LAPTOP | DESKTOP | MONITOR | MOBILE | ID_CARD | ACCESSORY
  serial_number            text,
  assigned_employee_id     text,
  assigned_employee_name   text,
  assigned_date            date,
  condition                text, -- EXCELLENT | GOOD | FAIR | DAMAGED
  status                   text, -- AVAILABLE | ASSIGNED | MAINTENANCE | RETIRED
  notes                    text,
  history                  jsonb,
  _extra                   jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "probationRecords" collection (type ProbationRecord).
create table if not exists crm.probation_records (
  id                  text not null,
  org_id              text not null,
  employee_id         text,
  employee_name       text,
  department          text,
  designation         text,
  start_date          text,
  probation_months    numeric,
  expected_end_date   text,
  actual_end_date     text,
  status              text, -- CONFIRMED | EXTENDED | ON_TRACK | REVIEW_PENDING | TERMINATED
  manager_name        text,
  review_score        numeric,
  decision_reason     text,
  _extra              jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position           double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "promotions" collection (type PromotionRecord).
create table if not exists crm.promotion_records (
  id                    text not null,
  org_id                text not null,
  employee_id           text,
  employee_name         text,
  current_designation   text,
  new_designation       text,
  current_department    text,
  new_department        text,
  current_ctc_lpa       numeric,
  new_ctc_lpa           numeric,
  effective_date        date,
  reason                text,
  status                text, -- APPROVED | REJECTED | PENDING | APPLIED
  requested_by_name     text,
  approved_by_name      text,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "transfers" collection (type TransferRecord).
create table if not exists crm.transfer_records (
  id                text not null,
  org_id            text not null,
  employee_id       text,
  employee_name     text,
  from_department   text,
  to_department     text,
  from_location     text,
  to_location       text,
  from_manager      text,
  to_manager        text,
  effective_date    date,
  reason            text,
  status            text, -- APPROVED | REJECTED | COMPLETED | PENDING
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "salaryRevisions" collection (type SalaryRevisionRecord).
create table if not exists crm.salary_revisions (
  id                  text not null,
  org_id              text not null,
  employee_id         text,
  employee_name       text,
  current_ctc         numeric,
  new_ctc             numeric,
  increment_percent   numeric,
  revision_type       text, -- ANNUAL_INCREMENT | PROMOTION | MARKET_ADJUSTMENT | CORRECTION
  effective_date      date,
  reason              text,
  status              text, -- APPROVED | REJECTED | PENDING | PROCESSED
  requested_by_name   text,
  _extra              jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position           double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "exitRecords" collection (type ExitRecord).
create table if not exists crm.exit_records (
  id                         text not null,
  org_id                     text not null,
  employee_id                text,
  employee_name              text,
  department                 text,
  resignation_date           date,
  notice_period_days         numeric,
  last_working_day           date,
  reason                     text,
  status                     text, -- PENDING_APPROVAL | COMPLETED | NOTICE_PERIOD | CLEARANCE | SETTLED | WITHDRAWN
  exit_interview_notes       text,
  clearance_checklist        jsonb,
  fnf_settled                boolean,
  fnf_amount_inr             numeric,
  fnf_paid                   boolean,
  experience_letter_issued   boolean,
  employee_feedback          jsonb,
  _extra                     jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                  double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "employeeRequests" collection (type EmployeeRequest).
create table if not exists crm.employee_requests (
  id                   text not null,
  org_id               text not null,
  employee_id          text,
  employee_name        text,
  department           text,
  type                 text, -- OTHER | EXPERIENCE_LETTER | SALARY_CERTIFICATE | ID_CARD | LEAVE | ATTENDANCE_CORRECTION | WFH | ADDRESS_CHANGE | BANK_CHANGE | NAME_CHANGE | IT_SUPPORT | GRIEVANCE
  description          text,
  priority             text, -- LOW | MEDIUM | HIGH | URGENT
  status               text, -- APPROVED | REJECTED | PENDING | WITHDRAWN | IN_REVIEW
  payload              jsonb,
  attachment_file_id   text,
  confidential         boolean,
  requested_at         timestamptz,
  reviewed_at          timestamptz,
  reviewed_by_name     text,
  comments             text,
  attachment_name      text,
  _extra               jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position            double precision not null default 0, -- list order the app expects
  primary key (id)
);
