-- ════════════════════════════════════════════════════════════
-- HR — attendance, shifts, leave, holidays
-- Daily attendance, shift rosters, regularisation and WFH requests, leave requests / balances / policies and the holiday calendar.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- One row per user per day; check_in / check_out keep the exact string the app writes.
create table if not exists crm.attendance_records (
  id                  text not null,
  org_id              text not null,
  user_id             text,
  date                date,
  status              text, -- ON_LEAVE | WFH | PRESENT | ABSENT | LATE | HALF_DAY
  check_in            text,
  check_out           text,
  mode                text, -- OFFICE | WFH
  late_by_minutes     numeric,
  worked_on_off_day   boolean,
  _extra              jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position           double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "shifts" collection (type ShiftSchedule).
create table if not exists crm.shift_schedules (
  id               text not null,
  org_id           text not null,
  name             text,
  code             text,
  start_time       text,
  end_time         text,
  grace_minutes    numeric,
  working_hours    numeric,
  assigned_count   numeric,
  is_rotational    boolean,
  status           text, -- ACTIVE | INACTIVE
  _extra           jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position        double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "attendanceCorrections" collection (type AttendanceCorrectionRecord).
create table if not exists crm.attendance_corrections (
  id                    text not null,
  org_id                text not null,
  employee_id           text,
  employee_name         text,
  date                  date,
  original_check_in     text,
  original_check_out    text,
  requested_check_in    text,
  requested_check_out   text,
  reason                text,
  status                text, -- APPROVED | REJECTED | PENDING
  reviewed_by_name      text,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "wfhRequests" collection (type WfhRecord).
create table if not exists crm.wfh_requests (
  id                 text not null,
  org_id             text not null,
  employee_id        text,
  employee_name      text,
  department         text,
  start_date         date,
  end_date           date,
  days               numeric,
  reason             text,
  status             text, -- APPROVED | REJECTED | PENDING
  reviewed_by_name   text,
  _extra             jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position          double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "leaveRequests" collection (type LeaveRequest).
create table if not exists crm.leave_requests (
  id                   text not null,
  org_id               text not null,
  user_id              text,
  leave_type           text, -- CASUAL | SICK | EARNED | UNPAID | COMP_OFF | MATERNITY | PATERNITY
  from_date            date,
  to_date              date,
  reason               text,
  status               text, -- APPROVED | CANCELLED | REJECTED | PENDING
  approver_id          text,
  decision_note        text,
  half_day             text, -- FIRST | SECOND
  days                 numeric,
  attachment_file_id   text,
  cancelled_at         timestamptz,
  cancel_reason        text,
  created_at           timestamptz,
  _extra               jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position            double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "leaveBalances" collection (type LeaveBalanceRecord).
create table if not exists crm.leave_balances (
  id                 text not null,
  org_id             text not null,
  employee_id        text,
  employee_name      text,
  department         text,
  casual_allowance   numeric,
  casual_used        numeric,
  sick_allowance     numeric,
  sick_used          numeric,
  earned_allowance   numeric,
  earned_used        numeric,
  carry_forward      numeric,
  _extra             jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position          double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "leavePolicies" collection (type LeavePolicyConfig).
create table if not exists crm.leave_policies (
  id                     text not null,
  leave_type             text, -- CASUAL | SICK | EARNED | UNPAID | MATERNITY | PATERNITY
  annual_allowance       numeric,
  carry_forward_max      numeric,
  encashment_allowed     boolean,
  min_notice_days        numeric,
  max_consecutive_days   numeric,
  probation_allowed      boolean,
  _extra                 jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position              double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "holidays" collection (type Holiday).
create table if not exists crm.holidays (
  id          text not null,
  org_id      text not null,
  date        date,
  name        text,
  type        text, -- NATIONAL | FESTIVAL | OPTIONAL
  locations   text[],
  _extra      jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position   double precision not null default 0, -- list order the app expects
  primary key (id)
);
