-- ════════════════════════════════════════════════════════════
-- HR — payroll, performance, learning, benefits
-- Monthly payroll runs, reviews and review cycles, goals/OKRs, training, benefits and enrolments, tax declarations and policy acknowledgements.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- Backs the "payrollRecords" collection (type PayrollRecord).
create table if not exists crm.payroll_records (
  id               text not null,
  org_id           text not null,
  employee_id      text,
  employee_name    text,
  employee_code    text,
  department       text,
  month            text,
  basic_salary     numeric,
  hra              numeric,
  allowances       numeric,
  bonuses          numeric,
  overtime         numeric,
  deductions       numeric,
  tax              numeric,
  net_salary       numeric,
  status           text, -- DRAFT | PAID | PROCESSED
  payment_date     date,
  payment_method   text,
  payslip_url      text,
  pf               numeric,
  esi              numeric,
  pt               numeric,
  lop_days         numeric,
  lop_amount       numeric,
  employer_pf      numeric,
  employer_esi     numeric,
  on_hold          boolean,
  hold_reason      text,
  _extra           jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position        double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "performanceReviews" collection (type PerformanceReview).
create table if not exists crm.performance_reviews (
  id                      text not null,
  org_id                  text not null,
  employee_id             text,
  employee_name           text,
  department              text,
  review_cycle            text,
  goals                   jsonb,
  manager_feedback        text,
  employee_feedback       text,
  rating                  numeric,
  status                  text, -- COMPLETED | GOALS_SET | SELF_REVIEW | MANAGER_REVIEW
  promotion_recommended   boolean,
  increment_percent       numeric,
  updated_at              timestamptz,
  _extra                  jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position               double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "reviewCycles" collection (type ReviewCycle).
create table if not exists crm.review_cycles (
  id                   text not null,
  org_id               text not null,
  title                text,
  period               text,
  type                 text, -- ANNUAL | QUARTERLY | PROBATION
  status               text, -- ACTIVE | COMPLETED | UPCOMING
  deadline             date,
  participants_count   numeric,
  _extra               jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position            double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "goals" collection (type GoalOkr).
create table if not exists crm.goals_okrs (
  id            text not null,
  org_id        text not null,
  title         text,
  description   text,
  owner_id      text,
  owner_name    text,
  department    text,
  type          text, -- INDIVIDUAL | TEAM | DEPARTMENT
  start_date    date,
  end_date      date,
  weight        numeric,
  progress      numeric,
  status        text, -- COMPLETED | IN_PROGRESS | NOT_STARTED | AT_RISK
  _extra        jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position     double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "trainingPrograms" collection (type TrainingProgram).
create table if not exists crm.training_programs (
  id                       text not null,
  org_id                   text not null,
  title                    text,
  course                   text,
  trainer                  text,
  start_date               date,
  end_date                 date,
  enrolled_employee_ids    text[],
  completed_employee_ids   text[],
  self_enroll_open         boolean,
  feedback                 jsonb,
  status                   text, -- COMPLETED | IN_PROGRESS | UPCOMING
  description              text,
  _extra                   jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "benefits" collection (type EmployeeBenefit).
create table if not exists crm.employee_benefits (
  id                text not null,
  org_id            text not null,
  title             text,
  category          text, -- INSURANCE | WELLNESS | MEAL | ALLOWANCE | COMMUTE
  provider          text,
  coverage_amount   text,
  enrolled_count    numeric,
  status            text, -- ACTIVE | INACTIVE
  description       text,
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "benefitEnrollments" collection (type BenefitEnrollment).
create table if not exists crm.benefit_enrollments (
  id            text not null,
  org_id        text not null,
  benefit_id    text,
  employee_id   text,
  status        text, -- ENROLLED | OPTED_OUT
  dependents    jsonb,
  updated_at    timestamptz,
  _extra        jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position     double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "taxDeclarations" collection (type TaxDeclaration).
create table if not exists crm.tax_declarations (
  id                   text not null,
  org_id               text not null,
  employee_id          text,
  fy                   text,
  regime               text, -- NEW | OLD
  sec80_c              numeric,
  sec80_d              numeric,
  hra_rent_paid        numeric,
  metro_city           boolean,
  home_loan_interest   numeric,
  nps80_ccd1_b         numeric,
  other_deductions     numeric,
  proof_file_ids       text[],
  status               text, -- DRAFT | REJECTED | VERIFIED | SUBMITTED
  review_note          text,
  reviewed_by_name     text,
  submitted_at         timestamptz,
  updated_at           timestamptz,
  _extra               jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position            double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "hrPolicies" collection (type HrPolicyItem).
create table if not exists crm.hr_policies (
  id                      text not null,
  org_id                  text not null,
  title                   text,
  category                text, -- LEAVE | WFH | ATTENDANCE | PAYROLL | CODE_OF_CONDUCT | BENEFITS
  version                 text,
  effective_date          date,
  acknowledgement_count   numeric,
  summary                 text,
  status                  text, -- DRAFT | ARCHIVED | PUBLISHED
  _extra                  jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position               double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "policyAcknowledgements" collection (type PolicyAcknowledgement).
create table if not exists crm.policy_acknowledgements (
  id                text not null,
  org_id            text not null,
  policy_id         text,
  version           text,
  user_id           text,
  acknowledged_at   timestamptz,
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);
