-- ════════════════════════════════════════════════════════════
-- Finance — billing, payables, ledger
-- Finance settings, invoices and receipts, recurring billing, expenses, vendors and bills, contractor assignments and timesheets, F&F, bank lines, journals and budgets.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- Backs the "financeSettings" collection (type FinanceSettings).
create table if not exists crm.finance_settings (
  org_id                                  text not null,
  gst_rate                                numeric,
  company_state_code                      text,
  sac_code                                text,
  invoice_prefix                          text,
  credit_note_prefix                      text,
  debit_note_prefix                       text,
  receipt_prefix                          text,
  default_credit_days                     numeric,
  company_legal_name                      text,
  company_address                         text,
  company_gstin                           text,
  company_pan                             text,
  lut_number                              text,
  bank_name                               text,
  bank_account_number                     text,
  bank_ifsc                               text,
  bank_accounts                           jsonb,
  reimbursement_limit_inr                 numeric,
  invoice_approval_threshold_inr          numeric,
  vendor_payment_approval_threshold_inr   numeric,
  reminder_days                           jsonb,
  expense_category_limits                 jsonb,
  commission_tds_pct                      numeric,
  recruiter_incentive_pct                 numeric,
  guarantee_days_default                  numeric,
  credit_hold_overdue_days                numeric,
  locked_until                            text,
  e_invoice_enabled                       boolean,
  payroll                                 jsonb,
  _extra                                  jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                               double precision not null default 0, -- list order the app expects
  primary key (org_id)
);

-- Backs the "invoices" collection (type Invoice).
create table if not exists crm.invoices (
  id                   text not null,
  org_id               text not null,
  invoice_number       text,
  financial_year       text,
  kind                 text, -- INVOICE | CREDIT_NOTE | DEBIT_NOTE
  client_id            text,
  client_name          text,
  client_gstin         text,
  place_of_supply      text,
  placement_id         text,
  placement_ids        text[],
  application_id       text,
  candidate_name       text,
  job_title            text,
  milestone            text, -- FULL | ON_OFFER | ON_JOINING | RETAINER | TIMESHEET | REBILL | MANUAL
  credit_note_for_id   text,
  recurring_id         text,
  line_items           jsonb,
  currency             text, -- INR | USD | EUR | GBP | AED | SGD
  fx_rate              numeric,
  discount             numeric,
  subtotal             numeric,
  tax_rate             numeric,
  tax                  jsonb,
  tax_amount           numeric,
  round_off            numeric,
  total                numeric,
  amount_paid          numeric,
  written_off          numeric,
  status               text, -- DRAFT | PENDING_APPROVAL | CANCELLED | PAID | SENT | PARTIALLY_PAID | OVERDUE | WRITTEN_OFF
  issue_date           date,
  due_date             date,
  sent_at              timestamptz,
  paid_at              timestamptz,
  payments             jsonb,
  reminders            jsonb,
  approved_by_name     text,
  irn                  text,
  ledger_id            text,
  notes                text,
  created_by_id        text,
  created_by_name      text,
  created_at           timestamptz,
  updated_at           timestamptz,
  _extra               jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position            double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "receipts" collection (type Receipt).
create table if not exists crm.receipts (
  id                 text not null,
  org_id             text not null,
  receipt_number     text,
  client_id          text,
  client_name        text,
  date               date,
  amount             numeric,
  tds_amount         numeric,
  method             text, -- BANK_TRANSFER | UPI | CHEQUE | CASH | CARD
  reference          text,
  bank_account_id    text,
  allocations        jsonb,
  unapplied          numeric,
  reconciled         boolean,
  recorded_by_name   text,
  created_at         timestamptz,
  _extra             jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position          double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "recurringInvoices" collection (type RecurringInvoice).
create table if not exists crm.recurring_invoices (
  id                text not null,
  org_id            text not null,
  client_id         text,
  description       text,
  amount            numeric,
  frequency         text, -- QUARTERLY | MONTHLY
  next_date         date,
  end_date          date,
  auto_send         boolean,
  active            boolean,
  created_by_name   text,
  created_at        timestamptz,
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "expenses" collection (type Expense).
create table if not exists crm.expenses (
  id                         text not null,
  org_id                     text not null,
  category                   text, -- OTHER | OFFICE | TRAVEL | SOFTWARE | RENT | MARKETING | JOB_BOARDS | UTILITIES | MEALS | TRAINING
  description                text,
  amount                     numeric,
  gst_amount                 numeric,
  vendor                     text,
  expense_date               date,
  is_reimbursement           boolean,
  submitted_by_id            text,
  submitted_by_name          text,
  receipt_url                text,
  receipt_file_id            text,
  billable                   boolean,
  client_id                  text,
  rebilled_invoice_id        text,
  policy_flag                text,
  status                     text, -- APPROVED | REJECTED | PENDING | PAID | PENDING_MANAGER
  manager_approved_by_name   text,
  approved_by_name           text,
  approved_at                timestamptz,
  rejection_reason           text,
  paid_at                    timestamptz,
  payment_reference          text,
  created_at                 timestamptz,
  _extra                     jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position                  double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "vendors" collection (type Vendor).
create table if not exists crm.vendors (
  id                    text not null,
  org_id                text not null,
  name                  text,
  category              text, -- OTHER | OFFICE | TRAVEL | SOFTWARE | RENT | MARKETING | JOB_BOARDS | UTILITIES | MEALS | TRAINING
  gstin                 text,
  pan                   text,
  email                 text,
  phone                 text,
  bank_name             text,
  bank_account_number   text,
  bank_ifsc             text,
  tds_section           text, -- 194C | 194J | 194I | NONE
  payment_terms_days    numeric,
  active                boolean,
  created_at            timestamptz,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "vendorBills" collection (type VendorBill).
create table if not exists crm.vendor_bills (
  id                    text not null,
  org_id                text not null,
  vendor_id             text,
  vendor_name           text,
  bill_number           text,
  bill_date             date,
  due_date              date,
  category              text, -- OTHER | OFFICE | TRAVEL | SOFTWARE | RENT | MARKETING | JOB_BOARDS | UTILITIES | MEALS | TRAINING
  description           text,
  amount                numeric,
  gst_amount            numeric,
  tds_section           text, -- 194C | 194J | 194I | NONE
  tds_amount            numeric,
  total                 numeric,
  payable               numeric,
  amount_paid           numeric,
  payments              jsonb,
  status                text, -- PENDING_APPROVAL | APPROVED | CANCELLED | PAID | PARTIALLY_PAID | OVERDUE
  recurring             boolean,
  recurring_next_date   date,
  file_id               text,
  approved_by_name      text,
  created_by_name       text,
  created_at            timestamptz,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "contractAssignments" collection (type ContractAssignment).
create table if not exists crm.contract_assignments (
  id                text not null,
  org_id            text not null,
  client_id         text,
  client_name       text,
  worker_name       text,
  worker_email      text,
  candidate_id      text,
  role              text,
  rate_type         text, -- MONTHLY | DAILY | HOURLY
  bill_rate         numeric,
  pay_rate          numeric,
  start_date        date,
  end_date          date,
  status            text, -- ACTIVE | ENDED
  recruiter_id      text,
  created_by_name   text,
  created_at        timestamptz,
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "timesheets" collection (type Timesheet).
create table if not exists crm.timesheets (
  id                  text not null,
  org_id              text not null,
  assignment_id       text,
  month               text,
  units               numeric,
  status              text, -- APPROVED | REJECTED | SUBMITTED | INVOICED
  bill_amount         numeric,
  pay_amount          numeric,
  invoice_id          text,
  contractor_paid     boolean,
  approved_by_name    text,
  submitted_by_name   text,
  created_at          timestamptz,
  _extra              jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position           double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "fnfPayments" collection (type FnfPayment).
create table if not exists crm.fnf_payments (
  id              text not null,
  org_id          text not null,
  exit_id         text,
  employee_id     text,
  employee_name   text,
  amount          numeric,
  status          text, -- PENDING | PAID
  paid_at         timestamptz,
  reference       text,
  created_at      timestamptz,
  _extra          jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position       double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "bankStatementLines" collection (type BankStatementLine).
create table if not exists crm.bank_statement_lines (
  id                text not null,
  org_id            text not null,
  bank_account_id   text,
  date              date,
  description       text,
  reference         text,
  debit             numeric,
  credit            numeric,
  matched_type      text, -- RECEIPT | PAYMENT | JOURNAL
  matched_id        text,
  imported_at       timestamptz,
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "manualJournals" collection (type ManualJournal).
create table if not exists crm.manual_journals (
  id                text not null,
  org_id            text not null,
  date              date,
  narration         text,
  lines             jsonb,
  created_by_name   text,
  created_at        timestamptz,
  _extra            jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position         double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "budgets" collection (type Budget).
create table if not exists crm.budgets (
  id          text not null,
  org_id      text not null,
  month       text,
  category    text,
  amount      numeric,
  _extra      jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position   double precision not null default 0, -- list order the app expects
  primary key (id)
);
