-- ════════════════════════════════════════════════════════════
-- Workspace — tasks, approvals, notifications, audit
-- Cross-role plumbing: Jira-style tasks with comments and history, announcements, in-app notifications, approval requests, audit trail, compliance, data quality, integrations, workflow rules, outgoing email and uploaded files.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

-- Jira-style tasks: key (ABS-12), type, status workflow, assignee, reporter (created_by_id), watchers, labels. Shown on Admin, HR, TA and Portal › Tasks.
create table if not exists crm.tasks (
  id                      text not null,
  org_id                  text not null,
  key                     text,
  type                    text, -- MEETING | TASK | FOLLOW_UP | CALL | DOCUMENTS | INTERVIEW
  status                  text, -- IN_PROGRESS | IN_REVIEW | TODO | BLOCKED | DONE
  assigned_to_id          text,
  created_by_id           text,
  title                   text,
  description             text,
  labels                  text[],
  watcher_ids             text[],
  start_date              date,
  due_date                date,
  estimate_hours          numeric,
  priority                text, -- LOW | MEDIUM | HIGH | URGENT
  related_type            text, -- EMPLOYEE | CANDIDATE | CLIENT | JOB
  related_id              text,
  linked_application_id   text,
  completed               boolean,
  completed_at            timestamptz,
  created_at              timestamptz,
  updated_at              timestamptz,
  _extra                  jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position               double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Comments on a task. mention_ids lists users @mentioned in the body.
create table if not exists crm.task_comments (
  id            text not null,
  org_id        text not null,
  task_id       text,
  author_id     text,
  body          text,
  mention_ids   text[],
  created_at    timestamptz,
  edited_at     timestamptz,
  _extra        jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position     double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Task history: creation, every field change (field / from_value / to_value) and comments.
create table if not exists crm.task_activity (
  id           text not null,
  org_id       text not null,
  task_id      text,
  actor_id     text,
  action       text, -- CREATED | UPDATED | COMMENTED
  field        text,
  from_value   text,
  to_value     text,
  created_at   timestamptz,
  _extra       jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position    double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "announcements" collection (type Announcement).
create table if not exists crm.announcements (
  id              text not null,
  org_id          text not null,
  title           text,
  body            text,
  audience        text[],
  pinned          boolean,
  created_by_id   text,
  created_at      timestamptz,
  _extra          jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position       double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- In-app bell notifications, one row per recipient.
create table if not exists crm.notifications (
  id           text not null,
  org_id       text not null,
  user_id      text,
  title        text,
  message      text,
  link         text,
  is_read      boolean,
  created_at   timestamptz,
  _extra       jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position    double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "approvals" collection (type ApprovalRequest).
create table if not exists crm.approval_requests (
  id                    text not null,
  org_id                text not null,
  type                  text, -- JOB_REQUISITION | OFFER_APPROVAL | SALARY_EXCEPTION | CANDIDATE_EXCEPTION | CLIENT_APPROVAL | INVOICE_APPROVAL | EXPENSE_APPROVAL | USER_ACCESS
  title                 text,
  requested_by_id       text,
  requested_by_name     text,
  requested_by_role     text,
  date                  text,
  priority              text, -- LOW | MEDIUM | HIGH | URGENT
  related_record_type   text, -- CANDIDATE | CLIENT | INVOICE | JOB | USER | EXPENSE
  related_record_id     text,
  related_record_name   text,
  description           text,
  supporting_doc_url    text,
  status                text, -- APPROVED | CANCELLED | REJECTED | PENDING | CHANGES_REQUESTED
  reviewed_by_id        text,
  reviewed_by_name      text,
  review_comment        text,
  reviewed_at           timestamptz,
  _extra                jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position             double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Append-only trail of who did what.
create table if not exists crm.audit_logs (
  id              text not null,
  org_id          text not null,
  actor_user_id   text,
  actor_role      text, -- SUPER_ADMIN | TA_MANAGER | TA_RECRUITER | AGENT | EMPLOYEE | HR_ADMIN | FINANCE_ADMIN
  action          text,
  entity          text,
  entity_id       text,
  detail          text,
  created_at      timestamptz,
  _extra          jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position       double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "complianceItems" collection (type ComplianceItem).
create table if not exists crm.compliance_items (
  id             text not null,
  org_id         text not null,
  category       text, -- CONSENT | DOCUMENT_EXPIRY | MISSING_DOC | RETENTION | DATA_REQUEST
  title          text,
  entity_type    text, -- EMPLOYEE | CANDIDATE | CLIENT
  entity_id      text,
  entity_name    text,
  severity       text, -- COMPLETED | PENDING | CRITICAL | WARNING
  due_date       text,
  status         text, -- IN_REVIEW | OPEN | RESOLVED | IGNORED
  detail         text,
  last_updated   text,
  _extra         jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position      double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "dataQualityIssues" collection (type DataQualityIssue).
create table if not exists crm.data_quality_issues (
  id                 text not null,
  org_id             text not null,
  type               text, -- DUPLICATE_CANDIDATE | DUPLICATE_CLIENT | DUPLICATE_JOB | INCOMPLETE_PROFILE | MISSING_RESUME | INVALID_CONTACT
  title              text,
  entity_type        text, -- CANDIDATE | CLIENT | JOB
  entity_id          text,
  entity_name        text,
  severity           text, -- LOW | MEDIUM | HIGH
  details            text,
  suggested_action   text,
  created_at         timestamptz,
  _extra             jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position          double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "integrationServices" collection (type IntegrationService).
create table if not exists crm.integration_services (
  id                  text not null,
  org_id              text not null,
  name                text,
  category            text, -- COMMUNICATION | RECRUITMENT | CALENDAR | STORAGE | FINANCE | TECHNICAL
  provider            text,
  status              text, -- CONNECTED | DISCONNECTED | ERROR | NEEDS_ATTENTION
  connected_account   text,
  last_sync_at        timestamptz,
  icon                text,
  description         text,
  config_summary      text,
  _extra              jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position           double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "workflows" collection (type WorkflowAutomationRule).
create table if not exists crm.workflow_rules (
  id              text not null,
  org_id          text not null,
  name            text,
  trigger         text,
  condition       text,
  approval_role   text,
  action          text,
  active          boolean,
  _extra          jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position       double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "emailOutbox" collection (type EmailMessage).
create table if not exists crm.email_outbox (
  id             text not null,
  org_id         text not null,
  "to"           text[],
  subject        text,
  html           text,
  related_type   text,
  related_id     text,
  attachments    text[],
  status         text, -- SENT | QUEUED | FAILED | LOGGED
  provider_id    text,
  error          text,
  sent_by_name   text,
  created_at     timestamptz,
  _extra         jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position      double precision not null default 0, -- list order the app expects
  primary key (id)
);

-- Backs the "storedFiles" collection (type StoredFile).
create table if not exists crm.stored_files (
  id              text not null,
  org_id          text not null,
  name            text,
  mime_type       text,
  size            numeric,
  data_base64     text,
  owner_user_id   text,
  purpose         text,
  created_at      timestamptz,
  _extra          jsonb not null default '{}'::jsonb, -- values that don't fit a typed column (kept losslessly)
  _position       double precision not null default 0, -- list order the app expects
  primary key (id)
);
