-- ════════════════════════════════════════════════════════════
-- Relationships and indexes
-- Foreign keys between CRM tables plus lookup indexes. Constraints are deferrable so the app can save related rows in any order within one transaction.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════


alter table crm.users drop constraint if exists users_org_id_fkey;
alter table crm.users add constraint users_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.users drop constraint if exists users_reporting_to_fkey;
alter table crm.users add constraint users_reporting_to_fkey
  foreign key (reporting_to) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.organization_settings drop constraint if exists organization_settings_org_id_fkey;
alter table crm.organization_settings add constraint organization_settings_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.clients drop constraint if exists clients_org_id_fkey;
alter table crm.clients add constraint clients_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.clients drop constraint if exists clients_account_manager_id_fkey;
alter table crm.clients add constraint clients_account_manager_id_fkey
  foreign key (account_manager_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.client_leads drop constraint if exists client_leads_org_id_fkey;
alter table crm.client_leads add constraint client_leads_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.client_leads drop constraint if exists client_leads_assigned_to_id_fkey;
alter table crm.client_leads add constraint client_leads_assigned_to_id_fkey
  foreign key (assigned_to_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.client_communications drop constraint if exists client_communications_org_id_fkey;
alter table crm.client_communications add constraint client_communications_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.client_communications drop constraint if exists client_communications_client_id_fkey;
alter table crm.client_communications add constraint client_communications_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.jobs drop constraint if exists jobs_org_id_fkey;
alter table crm.jobs add constraint jobs_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.jobs drop constraint if exists jobs_client_id_fkey;
alter table crm.jobs add constraint jobs_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.candidates drop constraint if exists candidates_org_id_fkey;
alter table crm.candidates add constraint candidates_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.candidates drop constraint if exists candidates_referred_by_user_id_fkey;
alter table crm.candidates add constraint candidates_referred_by_user_id_fkey
  foreign key (referred_by_user_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.applications drop constraint if exists applications_org_id_fkey;
alter table crm.applications add constraint applications_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.applications drop constraint if exists applications_candidate_id_fkey;
alter table crm.applications add constraint applications_candidate_id_fkey
  foreign key (candidate_id) references crm.candidates (id)
  on delete set null deferrable initially deferred;

alter table crm.applications drop constraint if exists applications_job_id_fkey;
alter table crm.applications add constraint applications_job_id_fkey
  foreign key (job_id) references crm.jobs (id)
  on delete set null deferrable initially deferred;

alter table crm.applications drop constraint if exists applications_recruiter_id_fkey;
alter table crm.applications add constraint applications_recruiter_id_fkey
  foreign key (recruiter_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.interviews drop constraint if exists interviews_org_id_fkey;
alter table crm.interviews add constraint interviews_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.interviews drop constraint if exists interviews_application_id_fkey;
alter table crm.interviews add constraint interviews_application_id_fkey
  foreign key (application_id) references crm.applications (id)
  on delete set null deferrable initially deferred;

alter table crm.placements drop constraint if exists placements_org_id_fkey;
alter table crm.placements add constraint placements_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.placements drop constraint if exists placements_candidate_id_fkey;
alter table crm.placements add constraint placements_candidate_id_fkey
  foreign key (candidate_id) references crm.candidates (id)
  on delete set null deferrable initially deferred;

alter table crm.placements drop constraint if exists placements_job_id_fkey;
alter table crm.placements add constraint placements_job_id_fkey
  foreign key (job_id) references crm.jobs (id)
  on delete set null deferrable initially deferred;

alter table crm.placements drop constraint if exists placements_client_id_fkey;
alter table crm.placements add constraint placements_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.message_templates drop constraint if exists message_templates_org_id_fkey;
alter table crm.message_templates add constraint message_templates_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.recruiter_targets drop constraint if exists recruiter_targets_org_id_fkey;
alter table crm.recruiter_targets add constraint recruiter_targets_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.agent_profiles drop constraint if exists agent_profiles_org_id_fkey;
alter table crm.agent_profiles add constraint agent_profiles_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.agent_profiles drop constraint if exists agent_profiles_user_id_fkey;
alter table crm.agent_profiles add constraint agent_profiles_user_id_fkey
  foreign key (user_id) references crm.users (id)
  on delete cascade deferrable initially deferred;

alter table crm.referrals drop constraint if exists referrals_org_id_fkey;
alter table crm.referrals add constraint referrals_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.referrals drop constraint if exists referrals_agent_id_fkey;
alter table crm.referrals add constraint referrals_agent_id_fkey
  foreign key (agent_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.referrals drop constraint if exists referrals_candidate_id_fkey;
alter table crm.referrals add constraint referrals_candidate_id_fkey
  foreign key (candidate_id) references crm.candidates (id)
  on delete set null deferrable initially deferred;

alter table crm.referrals drop constraint if exists referrals_job_id_fkey;
alter table crm.referrals add constraint referrals_job_id_fkey
  foreign key (job_id) references crm.jobs (id)
  on delete set null deferrable initially deferred;

alter table crm.referral_messages drop constraint if exists referral_messages_org_id_fkey;
alter table crm.referral_messages add constraint referral_messages_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.referral_messages drop constraint if exists referral_messages_referral_id_fkey;
alter table crm.referral_messages add constraint referral_messages_referral_id_fkey
  foreign key (referral_id) references crm.referrals (id)
  on delete set null deferrable initially deferred;

alter table crm.commission_ledger drop constraint if exists commission_ledger_org_id_fkey;
alter table crm.commission_ledger add constraint commission_ledger_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.commission_ledger drop constraint if exists commission_ledger_client_id_fkey;
alter table crm.commission_ledger add constraint commission_ledger_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.payouts drop constraint if exists payouts_org_id_fkey;
alter table crm.payouts add constraint payouts_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.payee_profiles drop constraint if exists payee_profiles_user_id_fkey;
alter table crm.payee_profiles add constraint payee_profiles_user_id_fkey
  foreign key (user_id) references crm.users (id)
  on delete cascade deferrable initially deferred;

alter table crm.employees drop constraint if exists employees_org_id_fkey;
alter table crm.employees add constraint employees_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.employees drop constraint if exists employees_user_id_fkey;
alter table crm.employees add constraint employees_user_id_fkey
  foreign key (user_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.employees drop constraint if exists employees_reporting_manager_id_fkey;
alter table crm.employees add constraint employees_reporting_manager_id_fkey
  foreign key (reporting_manager_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.onboarding_records drop constraint if exists onboarding_records_org_id_fkey;
alter table crm.onboarding_records add constraint onboarding_records_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.onboarding_records drop constraint if exists onboarding_records_candidate_id_fkey;
alter table crm.onboarding_records add constraint onboarding_records_candidate_id_fkey
  foreign key (candidate_id) references crm.candidates (id)
  on delete set null deferrable initially deferred;

alter table crm.employee_documents drop constraint if exists employee_documents_org_id_fkey;
alter table crm.employee_documents add constraint employee_documents_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.employee_documents drop constraint if exists employee_documents_employee_id_fkey;
alter table crm.employee_documents add constraint employee_documents_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.employee_assets drop constraint if exists employee_assets_org_id_fkey;
alter table crm.employee_assets add constraint employee_assets_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.probation_records drop constraint if exists probation_records_org_id_fkey;
alter table crm.probation_records add constraint probation_records_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.probation_records drop constraint if exists probation_records_employee_id_fkey;
alter table crm.probation_records add constraint probation_records_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.promotion_records drop constraint if exists promotion_records_org_id_fkey;
alter table crm.promotion_records add constraint promotion_records_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.promotion_records drop constraint if exists promotion_records_employee_id_fkey;
alter table crm.promotion_records add constraint promotion_records_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.transfer_records drop constraint if exists transfer_records_org_id_fkey;
alter table crm.transfer_records add constraint transfer_records_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.transfer_records drop constraint if exists transfer_records_employee_id_fkey;
alter table crm.transfer_records add constraint transfer_records_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.salary_revisions drop constraint if exists salary_revisions_org_id_fkey;
alter table crm.salary_revisions add constraint salary_revisions_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.salary_revisions drop constraint if exists salary_revisions_employee_id_fkey;
alter table crm.salary_revisions add constraint salary_revisions_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.exit_records drop constraint if exists exit_records_org_id_fkey;
alter table crm.exit_records add constraint exit_records_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.exit_records drop constraint if exists exit_records_employee_id_fkey;
alter table crm.exit_records add constraint exit_records_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.employee_requests drop constraint if exists employee_requests_org_id_fkey;
alter table crm.employee_requests add constraint employee_requests_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.employee_requests drop constraint if exists employee_requests_employee_id_fkey;
alter table crm.employee_requests add constraint employee_requests_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.attendance_records drop constraint if exists attendance_records_org_id_fkey;
alter table crm.attendance_records add constraint attendance_records_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.attendance_records drop constraint if exists attendance_records_user_id_fkey;
alter table crm.attendance_records add constraint attendance_records_user_id_fkey
  foreign key (user_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.shift_schedules drop constraint if exists shift_schedules_org_id_fkey;
alter table crm.shift_schedules add constraint shift_schedules_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.attendance_corrections drop constraint if exists attendance_corrections_org_id_fkey;
alter table crm.attendance_corrections add constraint attendance_corrections_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.attendance_corrections drop constraint if exists attendance_corrections_employee_id_fkey;
alter table crm.attendance_corrections add constraint attendance_corrections_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.wfh_requests drop constraint if exists wfh_requests_org_id_fkey;
alter table crm.wfh_requests add constraint wfh_requests_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.wfh_requests drop constraint if exists wfh_requests_employee_id_fkey;
alter table crm.wfh_requests add constraint wfh_requests_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.leave_requests drop constraint if exists leave_requests_org_id_fkey;
alter table crm.leave_requests add constraint leave_requests_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.leave_requests drop constraint if exists leave_requests_user_id_fkey;
alter table crm.leave_requests add constraint leave_requests_user_id_fkey
  foreign key (user_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.leave_balances drop constraint if exists leave_balances_org_id_fkey;
alter table crm.leave_balances add constraint leave_balances_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.leave_balances drop constraint if exists leave_balances_employee_id_fkey;
alter table crm.leave_balances add constraint leave_balances_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.holidays drop constraint if exists holidays_org_id_fkey;
alter table crm.holidays add constraint holidays_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.payroll_records drop constraint if exists payroll_records_org_id_fkey;
alter table crm.payroll_records add constraint payroll_records_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.payroll_records drop constraint if exists payroll_records_employee_id_fkey;
alter table crm.payroll_records add constraint payroll_records_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.performance_reviews drop constraint if exists performance_reviews_org_id_fkey;
alter table crm.performance_reviews add constraint performance_reviews_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.performance_reviews drop constraint if exists performance_reviews_employee_id_fkey;
alter table crm.performance_reviews add constraint performance_reviews_employee_id_fkey
  foreign key (employee_id) references crm.employees (id)
  on delete set null deferrable initially deferred;

alter table crm.review_cycles drop constraint if exists review_cycles_org_id_fkey;
alter table crm.review_cycles add constraint review_cycles_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.goals_okrs drop constraint if exists goals_okrs_org_id_fkey;
alter table crm.goals_okrs add constraint goals_okrs_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.training_programs drop constraint if exists training_programs_org_id_fkey;
alter table crm.training_programs add constraint training_programs_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.employee_benefits drop constraint if exists employee_benefits_org_id_fkey;
alter table crm.employee_benefits add constraint employee_benefits_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.benefit_enrollments drop constraint if exists benefit_enrollments_org_id_fkey;
alter table crm.benefit_enrollments add constraint benefit_enrollments_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.tax_declarations drop constraint if exists tax_declarations_org_id_fkey;
alter table crm.tax_declarations add constraint tax_declarations_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.hr_policies drop constraint if exists hr_policies_org_id_fkey;
alter table crm.hr_policies add constraint hr_policies_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.policy_acknowledgements drop constraint if exists policy_acknowledgements_org_id_fkey;
alter table crm.policy_acknowledgements add constraint policy_acknowledgements_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.policy_acknowledgements drop constraint if exists policy_acknowledgements_user_id_fkey;
alter table crm.policy_acknowledgements add constraint policy_acknowledgements_user_id_fkey
  foreign key (user_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.finance_settings drop constraint if exists finance_settings_org_id_fkey;
alter table crm.finance_settings add constraint finance_settings_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.invoices drop constraint if exists invoices_org_id_fkey;
alter table crm.invoices add constraint invoices_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.invoices drop constraint if exists invoices_client_id_fkey;
alter table crm.invoices add constraint invoices_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.receipts drop constraint if exists receipts_org_id_fkey;
alter table crm.receipts add constraint receipts_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.receipts drop constraint if exists receipts_client_id_fkey;
alter table crm.receipts add constraint receipts_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.recurring_invoices drop constraint if exists recurring_invoices_org_id_fkey;
alter table crm.recurring_invoices add constraint recurring_invoices_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.recurring_invoices drop constraint if exists recurring_invoices_client_id_fkey;
alter table crm.recurring_invoices add constraint recurring_invoices_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.expenses drop constraint if exists expenses_org_id_fkey;
alter table crm.expenses add constraint expenses_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.vendors drop constraint if exists vendors_org_id_fkey;
alter table crm.vendors add constraint vendors_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.vendor_bills drop constraint if exists vendor_bills_org_id_fkey;
alter table crm.vendor_bills add constraint vendor_bills_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.vendor_bills drop constraint if exists vendor_bills_vendor_id_fkey;
alter table crm.vendor_bills add constraint vendor_bills_vendor_id_fkey
  foreign key (vendor_id) references crm.vendors (id)
  on delete set null deferrable initially deferred;

alter table crm.contract_assignments drop constraint if exists contract_assignments_org_id_fkey;
alter table crm.contract_assignments add constraint contract_assignments_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.contract_assignments drop constraint if exists contract_assignments_client_id_fkey;
alter table crm.contract_assignments add constraint contract_assignments_client_id_fkey
  foreign key (client_id) references crm.clients (id)
  on delete set null deferrable initially deferred;

alter table crm.contract_assignments drop constraint if exists contract_assignments_recruiter_id_fkey;
alter table crm.contract_assignments add constraint contract_assignments_recruiter_id_fkey
  foreign key (recruiter_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.timesheets drop constraint if exists timesheets_org_id_fkey;
alter table crm.timesheets add constraint timesheets_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.timesheets drop constraint if exists timesheets_assignment_id_fkey;
alter table crm.timesheets add constraint timesheets_assignment_id_fkey
  foreign key (assignment_id) references crm.contract_assignments (id)
  on delete set null deferrable initially deferred;

alter table crm.fnf_payments drop constraint if exists fnf_payments_org_id_fkey;
alter table crm.fnf_payments add constraint fnf_payments_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.bank_statement_lines drop constraint if exists bank_statement_lines_org_id_fkey;
alter table crm.bank_statement_lines add constraint bank_statement_lines_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.manual_journals drop constraint if exists manual_journals_org_id_fkey;
alter table crm.manual_journals add constraint manual_journals_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.budgets drop constraint if exists budgets_org_id_fkey;
alter table crm.budgets add constraint budgets_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.tasks drop constraint if exists tasks_org_id_fkey;
alter table crm.tasks add constraint tasks_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.tasks drop constraint if exists tasks_assigned_to_id_fkey;
alter table crm.tasks add constraint tasks_assigned_to_id_fkey
  foreign key (assigned_to_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.tasks drop constraint if exists tasks_created_by_id_fkey;
alter table crm.tasks add constraint tasks_created_by_id_fkey
  foreign key (created_by_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.announcements drop constraint if exists announcements_org_id_fkey;
alter table crm.announcements add constraint announcements_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.announcements drop constraint if exists announcements_created_by_id_fkey;
alter table crm.announcements add constraint announcements_created_by_id_fkey
  foreign key (created_by_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.notifications drop constraint if exists notifications_org_id_fkey;
alter table crm.notifications add constraint notifications_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.notifications drop constraint if exists notifications_user_id_fkey;
alter table crm.notifications add constraint notifications_user_id_fkey
  foreign key (user_id) references crm.users (id)
  on delete set null deferrable initially deferred;

alter table crm.approval_requests drop constraint if exists approval_requests_org_id_fkey;
alter table crm.approval_requests add constraint approval_requests_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.audit_logs drop constraint if exists audit_logs_org_id_fkey;
alter table crm.audit_logs add constraint audit_logs_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.compliance_items drop constraint if exists compliance_items_org_id_fkey;
alter table crm.compliance_items add constraint compliance_items_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.data_quality_issues drop constraint if exists data_quality_issues_org_id_fkey;
alter table crm.data_quality_issues add constraint data_quality_issues_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.integration_services drop constraint if exists integration_services_org_id_fkey;
alter table crm.integration_services add constraint integration_services_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.workflow_rules drop constraint if exists workflow_rules_org_id_fkey;
alter table crm.workflow_rules add constraint workflow_rules_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.email_outbox drop constraint if exists email_outbox_org_id_fkey;
alter table crm.email_outbox add constraint email_outbox_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.stored_files drop constraint if exists stored_files_org_id_fkey;
alter table crm.stored_files add constraint stored_files_org_id_fkey
  foreign key (org_id) references crm.organizations (id)
  on delete cascade deferrable initially deferred;

alter table crm.stored_files drop constraint if exists stored_files_owner_user_id_fkey;
alter table crm.stored_files add constraint stored_files_owner_user_id_fkey
  foreign key (owner_user_id) references crm.users (id)
  on delete set null deferrable initially deferred;

-- Lookup indexes on every relationship column
create index if not exists users_org_id_idx on crm.users (org_id);
create index if not exists users_reporting_to_idx on crm.users (reporting_to);
create index if not exists clients_org_id_idx on crm.clients (org_id);
create index if not exists clients_account_manager_id_idx on crm.clients (account_manager_id);
create index if not exists client_leads_org_id_idx on crm.client_leads (org_id);
create index if not exists client_leads_assigned_to_id_idx on crm.client_leads (assigned_to_id);
create index if not exists client_communications_org_id_idx on crm.client_communications (org_id);
create index if not exists client_communications_client_id_idx on crm.client_communications (client_id);
create index if not exists jobs_org_id_idx on crm.jobs (org_id);
create index if not exists jobs_client_id_idx on crm.jobs (client_id);
create index if not exists candidates_org_id_idx on crm.candidates (org_id);
create index if not exists candidates_referred_by_user_id_idx on crm.candidates (referred_by_user_id);
create index if not exists applications_org_id_idx on crm.applications (org_id);
create index if not exists applications_candidate_id_idx on crm.applications (candidate_id);
create index if not exists applications_job_id_idx on crm.applications (job_id);
create index if not exists applications_recruiter_id_idx on crm.applications (recruiter_id);
create index if not exists interviews_org_id_idx on crm.interviews (org_id);
create index if not exists interviews_application_id_idx on crm.interviews (application_id);
create index if not exists placements_org_id_idx on crm.placements (org_id);
create index if not exists placements_candidate_id_idx on crm.placements (candidate_id);
create index if not exists placements_job_id_idx on crm.placements (job_id);
create index if not exists placements_client_id_idx on crm.placements (client_id);
create index if not exists message_templates_org_id_idx on crm.message_templates (org_id);
create index if not exists recruiter_targets_org_id_idx on crm.recruiter_targets (org_id);
create index if not exists agent_profiles_org_id_idx on crm.agent_profiles (org_id);
create index if not exists referrals_org_id_idx on crm.referrals (org_id);
create index if not exists referrals_agent_id_idx on crm.referrals (agent_id);
create index if not exists referrals_candidate_id_idx on crm.referrals (candidate_id);
create index if not exists referrals_job_id_idx on crm.referrals (job_id);
create index if not exists referral_messages_org_id_idx on crm.referral_messages (org_id);
create index if not exists referral_messages_referral_id_idx on crm.referral_messages (referral_id);
create index if not exists commission_ledger_org_id_idx on crm.commission_ledger (org_id);
create index if not exists commission_ledger_client_id_idx on crm.commission_ledger (client_id);
create index if not exists payouts_org_id_idx on crm.payouts (org_id);
create index if not exists employees_org_id_idx on crm.employees (org_id);
create index if not exists employees_user_id_idx on crm.employees (user_id);
create index if not exists employees_reporting_manager_id_idx on crm.employees (reporting_manager_id);
create index if not exists onboarding_records_org_id_idx on crm.onboarding_records (org_id);
create index if not exists onboarding_records_candidate_id_idx on crm.onboarding_records (candidate_id);
create index if not exists employee_documents_org_id_idx on crm.employee_documents (org_id);
create index if not exists employee_documents_employee_id_idx on crm.employee_documents (employee_id);
create index if not exists employee_assets_org_id_idx on crm.employee_assets (org_id);
create index if not exists probation_records_org_id_idx on crm.probation_records (org_id);
create index if not exists probation_records_employee_id_idx on crm.probation_records (employee_id);
create index if not exists promotion_records_org_id_idx on crm.promotion_records (org_id);
create index if not exists promotion_records_employee_id_idx on crm.promotion_records (employee_id);
create index if not exists transfer_records_org_id_idx on crm.transfer_records (org_id);
create index if not exists transfer_records_employee_id_idx on crm.transfer_records (employee_id);
create index if not exists salary_revisions_org_id_idx on crm.salary_revisions (org_id);
create index if not exists salary_revisions_employee_id_idx on crm.salary_revisions (employee_id);
create index if not exists exit_records_org_id_idx on crm.exit_records (org_id);
create index if not exists exit_records_employee_id_idx on crm.exit_records (employee_id);
create index if not exists employee_requests_org_id_idx on crm.employee_requests (org_id);
create index if not exists employee_requests_employee_id_idx on crm.employee_requests (employee_id);
create index if not exists attendance_records_org_id_idx on crm.attendance_records (org_id);
create index if not exists attendance_records_user_id_idx on crm.attendance_records (user_id);
create index if not exists shift_schedules_org_id_idx on crm.shift_schedules (org_id);
create index if not exists attendance_corrections_org_id_idx on crm.attendance_corrections (org_id);
create index if not exists attendance_corrections_employee_id_idx on crm.attendance_corrections (employee_id);
create index if not exists wfh_requests_org_id_idx on crm.wfh_requests (org_id);
create index if not exists wfh_requests_employee_id_idx on crm.wfh_requests (employee_id);
create index if not exists leave_requests_org_id_idx on crm.leave_requests (org_id);
create index if not exists leave_requests_user_id_idx on crm.leave_requests (user_id);
create index if not exists leave_balances_org_id_idx on crm.leave_balances (org_id);
create index if not exists leave_balances_employee_id_idx on crm.leave_balances (employee_id);
create index if not exists holidays_org_id_idx on crm.holidays (org_id);
create index if not exists payroll_records_org_id_idx on crm.payroll_records (org_id);
create index if not exists payroll_records_employee_id_idx on crm.payroll_records (employee_id);
create index if not exists performance_reviews_org_id_idx on crm.performance_reviews (org_id);
create index if not exists performance_reviews_employee_id_idx on crm.performance_reviews (employee_id);
create index if not exists review_cycles_org_id_idx on crm.review_cycles (org_id);
create index if not exists goals_okrs_org_id_idx on crm.goals_okrs (org_id);
create index if not exists training_programs_org_id_idx on crm.training_programs (org_id);
create index if not exists employee_benefits_org_id_idx on crm.employee_benefits (org_id);
create index if not exists benefit_enrollments_org_id_idx on crm.benefit_enrollments (org_id);
create index if not exists tax_declarations_org_id_idx on crm.tax_declarations (org_id);
create index if not exists hr_policies_org_id_idx on crm.hr_policies (org_id);
create index if not exists policy_acknowledgements_org_id_idx on crm.policy_acknowledgements (org_id);
create index if not exists policy_acknowledgements_user_id_idx on crm.policy_acknowledgements (user_id);
create index if not exists invoices_org_id_idx on crm.invoices (org_id);
create index if not exists invoices_client_id_idx on crm.invoices (client_id);
create index if not exists receipts_org_id_idx on crm.receipts (org_id);
create index if not exists receipts_client_id_idx on crm.receipts (client_id);
create index if not exists recurring_invoices_org_id_idx on crm.recurring_invoices (org_id);
create index if not exists recurring_invoices_client_id_idx on crm.recurring_invoices (client_id);
create index if not exists expenses_org_id_idx on crm.expenses (org_id);
create index if not exists vendors_org_id_idx on crm.vendors (org_id);
create index if not exists vendor_bills_org_id_idx on crm.vendor_bills (org_id);
create index if not exists vendor_bills_vendor_id_idx on crm.vendor_bills (vendor_id);
create index if not exists contract_assignments_org_id_idx on crm.contract_assignments (org_id);
create index if not exists contract_assignments_client_id_idx on crm.contract_assignments (client_id);
create index if not exists contract_assignments_recruiter_id_idx on crm.contract_assignments (recruiter_id);
create index if not exists timesheets_org_id_idx on crm.timesheets (org_id);
create index if not exists timesheets_assignment_id_idx on crm.timesheets (assignment_id);
create index if not exists fnf_payments_org_id_idx on crm.fnf_payments (org_id);
create index if not exists bank_statement_lines_org_id_idx on crm.bank_statement_lines (org_id);
create index if not exists manual_journals_org_id_idx on crm.manual_journals (org_id);
create index if not exists budgets_org_id_idx on crm.budgets (org_id);
create index if not exists tasks_org_id_idx on crm.tasks (org_id);
create index if not exists tasks_assigned_to_id_idx on crm.tasks (assigned_to_id);
create index if not exists tasks_created_by_id_idx on crm.tasks (created_by_id);
create index if not exists announcements_org_id_idx on crm.announcements (org_id);
create index if not exists announcements_created_by_id_idx on crm.announcements (created_by_id);
create index if not exists notifications_org_id_idx on crm.notifications (org_id);
create index if not exists notifications_user_id_idx on crm.notifications (user_id);
create index if not exists approval_requests_org_id_idx on crm.approval_requests (org_id);
create index if not exists audit_logs_org_id_idx on crm.audit_logs (org_id);
create index if not exists compliance_items_org_id_idx on crm.compliance_items (org_id);
create index if not exists data_quality_issues_org_id_idx on crm.data_quality_issues (org_id);
create index if not exists integration_services_org_id_idx on crm.integration_services (org_id);
create index if not exists workflow_rules_org_id_idx on crm.workflow_rules (org_id);
create index if not exists email_outbox_org_id_idx on crm.email_outbox (org_id);
create index if not exists stored_files_org_id_idx on crm.stored_files (org_id);
create index if not exists stored_files_owner_user_id_idx on crm.stored_files (owner_user_id);

-- Ordering index used when the app loads each table
create index if not exists organizations_position_idx on crm.organizations (_position);
create index if not exists users_position_idx on crm.users (_position);
create index if not exists organization_settings_position_idx on crm.organization_settings (_position);
create index if not exists clients_position_idx on crm.clients (_position);
create index if not exists client_leads_position_idx on crm.client_leads (_position);
create index if not exists client_communications_position_idx on crm.client_communications (_position);
create index if not exists jobs_position_idx on crm.jobs (_position);
create index if not exists candidates_position_idx on crm.candidates (_position);
create index if not exists applications_position_idx on crm.applications (_position);
create index if not exists interviews_position_idx on crm.interviews (_position);
create index if not exists placements_position_idx on crm.placements (_position);
create index if not exists message_templates_position_idx on crm.message_templates (_position);
create index if not exists recruiter_targets_position_idx on crm.recruiter_targets (_position);
create index if not exists agent_profiles_position_idx on crm.agent_profiles (_position);
create index if not exists referrals_position_idx on crm.referrals (_position);
create index if not exists referral_messages_position_idx on crm.referral_messages (_position);
create index if not exists commission_ledger_position_idx on crm.commission_ledger (_position);
create index if not exists payouts_position_idx on crm.payouts (_position);
create index if not exists payee_profiles_position_idx on crm.payee_profiles (_position);
create index if not exists employees_position_idx on crm.employees (_position);
create index if not exists onboarding_records_position_idx on crm.onboarding_records (_position);
create index if not exists employee_documents_position_idx on crm.employee_documents (_position);
create index if not exists employee_assets_position_idx on crm.employee_assets (_position);
create index if not exists probation_records_position_idx on crm.probation_records (_position);
create index if not exists promotion_records_position_idx on crm.promotion_records (_position);
create index if not exists transfer_records_position_idx on crm.transfer_records (_position);
create index if not exists salary_revisions_position_idx on crm.salary_revisions (_position);
create index if not exists exit_records_position_idx on crm.exit_records (_position);
create index if not exists employee_requests_position_idx on crm.employee_requests (_position);
create index if not exists attendance_records_position_idx on crm.attendance_records (_position);
create index if not exists shift_schedules_position_idx on crm.shift_schedules (_position);
create index if not exists attendance_corrections_position_idx on crm.attendance_corrections (_position);
create index if not exists wfh_requests_position_idx on crm.wfh_requests (_position);
create index if not exists leave_requests_position_idx on crm.leave_requests (_position);
create index if not exists leave_balances_position_idx on crm.leave_balances (_position);
create index if not exists leave_policies_position_idx on crm.leave_policies (_position);
create index if not exists holidays_position_idx on crm.holidays (_position);
create index if not exists payroll_records_position_idx on crm.payroll_records (_position);
create index if not exists performance_reviews_position_idx on crm.performance_reviews (_position);
create index if not exists review_cycles_position_idx on crm.review_cycles (_position);
create index if not exists goals_okrs_position_idx on crm.goals_okrs (_position);
create index if not exists training_programs_position_idx on crm.training_programs (_position);
create index if not exists employee_benefits_position_idx on crm.employee_benefits (_position);
create index if not exists benefit_enrollments_position_idx on crm.benefit_enrollments (_position);
create index if not exists tax_declarations_position_idx on crm.tax_declarations (_position);
create index if not exists hr_policies_position_idx on crm.hr_policies (_position);
create index if not exists policy_acknowledgements_position_idx on crm.policy_acknowledgements (_position);
create index if not exists finance_settings_position_idx on crm.finance_settings (_position);
create index if not exists invoices_position_idx on crm.invoices (_position);
create index if not exists receipts_position_idx on crm.receipts (_position);
create index if not exists recurring_invoices_position_idx on crm.recurring_invoices (_position);
create index if not exists expenses_position_idx on crm.expenses (_position);
create index if not exists vendors_position_idx on crm.vendors (_position);
create index if not exists vendor_bills_position_idx on crm.vendor_bills (_position);
create index if not exists contract_assignments_position_idx on crm.contract_assignments (_position);
create index if not exists timesheets_position_idx on crm.timesheets (_position);
create index if not exists fnf_payments_position_idx on crm.fnf_payments (_position);
create index if not exists bank_statement_lines_position_idx on crm.bank_statement_lines (_position);
create index if not exists manual_journals_position_idx on crm.manual_journals (_position);
create index if not exists budgets_position_idx on crm.budgets (_position);
create index if not exists tasks_position_idx on crm.tasks (_position);
create index if not exists announcements_position_idx on crm.announcements (_position);
create index if not exists notifications_position_idx on crm.notifications (_position);
create index if not exists approval_requests_position_idx on crm.approval_requests (_position);
create index if not exists audit_logs_position_idx on crm.audit_logs (_position);
create index if not exists compliance_items_position_idx on crm.compliance_items (_position);
create index if not exists data_quality_issues_position_idx on crm.data_quality_issues (_position);
create index if not exists integration_services_position_idx on crm.integration_services (_position);
create index if not exists workflow_rules_position_idx on crm.workflow_rules (_position);
create index if not exists email_outbox_position_idx on crm.email_outbox (_position);
create index if not exists stored_files_position_idx on crm.stored_files (_position);
