-- ════════════════════════════════════════════════════════════
-- Change tracking and access
-- Every write bumps a per-table version so each running app instance knows when to reload a table. RLS is on with no policies: only the server (postgres role) can touch CRM data.
-- Generated by scripts/db/generate.ts — edit config.ts / types.ts, then re-run.
-- ════════════════════════════════════════════════════════════

create table if not exists crm._sync_state (
  table_name text primary key,
  version    bigint not null default 0,
  changed_at timestamptz not null default now()
);

create or replace function crm.bump_sync_version() returns trigger
language plpgsql as $$
begin
  insert into crm._sync_state as s (table_name, version, changed_at)
  values (tg_table_name, 1, now())
  on conflict (table_name) do update set version = s.version + 1, changed_at = now();
  return null;
end $$;

drop trigger if exists organizations_sync on crm.organizations;
create trigger organizations_sync after insert or update or delete or truncate on crm.organizations
  for each statement execute function crm.bump_sync_version();
drop trigger if exists users_sync on crm.users;
create trigger users_sync after insert or update or delete or truncate on crm.users
  for each statement execute function crm.bump_sync_version();
drop trigger if exists organization_settings_sync on crm.organization_settings;
create trigger organization_settings_sync after insert or update or delete or truncate on crm.organization_settings
  for each statement execute function crm.bump_sync_version();
drop trigger if exists clients_sync on crm.clients;
create trigger clients_sync after insert or update or delete or truncate on crm.clients
  for each statement execute function crm.bump_sync_version();
drop trigger if exists client_leads_sync on crm.client_leads;
create trigger client_leads_sync after insert or update or delete or truncate on crm.client_leads
  for each statement execute function crm.bump_sync_version();
drop trigger if exists client_communications_sync on crm.client_communications;
create trigger client_communications_sync after insert or update or delete or truncate on crm.client_communications
  for each statement execute function crm.bump_sync_version();
drop trigger if exists jobs_sync on crm.jobs;
create trigger jobs_sync after insert or update or delete or truncate on crm.jobs
  for each statement execute function crm.bump_sync_version();
drop trigger if exists candidates_sync on crm.candidates;
create trigger candidates_sync after insert or update or delete or truncate on crm.candidates
  for each statement execute function crm.bump_sync_version();
drop trigger if exists applications_sync on crm.applications;
create trigger applications_sync after insert or update or delete or truncate on crm.applications
  for each statement execute function crm.bump_sync_version();
drop trigger if exists interviews_sync on crm.interviews;
create trigger interviews_sync after insert or update or delete or truncate on crm.interviews
  for each statement execute function crm.bump_sync_version();
drop trigger if exists placements_sync on crm.placements;
create trigger placements_sync after insert or update or delete or truncate on crm.placements
  for each statement execute function crm.bump_sync_version();
drop trigger if exists message_templates_sync on crm.message_templates;
create trigger message_templates_sync after insert or update or delete or truncate on crm.message_templates
  for each statement execute function crm.bump_sync_version();
drop trigger if exists recruiter_targets_sync on crm.recruiter_targets;
create trigger recruiter_targets_sync after insert or update or delete or truncate on crm.recruiter_targets
  for each statement execute function crm.bump_sync_version();
drop trigger if exists agent_profiles_sync on crm.agent_profiles;
create trigger agent_profiles_sync after insert or update or delete or truncate on crm.agent_profiles
  for each statement execute function crm.bump_sync_version();
drop trigger if exists referrals_sync on crm.referrals;
create trigger referrals_sync after insert or update or delete or truncate on crm.referrals
  for each statement execute function crm.bump_sync_version();
drop trigger if exists referral_messages_sync on crm.referral_messages;
create trigger referral_messages_sync after insert or update or delete or truncate on crm.referral_messages
  for each statement execute function crm.bump_sync_version();
drop trigger if exists commission_ledger_sync on crm.commission_ledger;
create trigger commission_ledger_sync after insert or update or delete or truncate on crm.commission_ledger
  for each statement execute function crm.bump_sync_version();
drop trigger if exists payouts_sync on crm.payouts;
create trigger payouts_sync after insert or update or delete or truncate on crm.payouts
  for each statement execute function crm.bump_sync_version();
drop trigger if exists payee_profiles_sync on crm.payee_profiles;
create trigger payee_profiles_sync after insert or update or delete or truncate on crm.payee_profiles
  for each statement execute function crm.bump_sync_version();
drop trigger if exists employees_sync on crm.employees;
create trigger employees_sync after insert or update or delete or truncate on crm.employees
  for each statement execute function crm.bump_sync_version();
drop trigger if exists onboarding_records_sync on crm.onboarding_records;
create trigger onboarding_records_sync after insert or update or delete or truncate on crm.onboarding_records
  for each statement execute function crm.bump_sync_version();
drop trigger if exists employee_documents_sync on crm.employee_documents;
create trigger employee_documents_sync after insert or update or delete or truncate on crm.employee_documents
  for each statement execute function crm.bump_sync_version();
drop trigger if exists employee_assets_sync on crm.employee_assets;
create trigger employee_assets_sync after insert or update or delete or truncate on crm.employee_assets
  for each statement execute function crm.bump_sync_version();
drop trigger if exists probation_records_sync on crm.probation_records;
create trigger probation_records_sync after insert or update or delete or truncate on crm.probation_records
  for each statement execute function crm.bump_sync_version();
drop trigger if exists promotion_records_sync on crm.promotion_records;
create trigger promotion_records_sync after insert or update or delete or truncate on crm.promotion_records
  for each statement execute function crm.bump_sync_version();
drop trigger if exists transfer_records_sync on crm.transfer_records;
create trigger transfer_records_sync after insert or update or delete or truncate on crm.transfer_records
  for each statement execute function crm.bump_sync_version();
drop trigger if exists salary_revisions_sync on crm.salary_revisions;
create trigger salary_revisions_sync after insert or update or delete or truncate on crm.salary_revisions
  for each statement execute function crm.bump_sync_version();
drop trigger if exists exit_records_sync on crm.exit_records;
create trigger exit_records_sync after insert or update or delete or truncate on crm.exit_records
  for each statement execute function crm.bump_sync_version();
drop trigger if exists employee_requests_sync on crm.employee_requests;
create trigger employee_requests_sync after insert or update or delete or truncate on crm.employee_requests
  for each statement execute function crm.bump_sync_version();
drop trigger if exists attendance_records_sync on crm.attendance_records;
create trigger attendance_records_sync after insert or update or delete or truncate on crm.attendance_records
  for each statement execute function crm.bump_sync_version();
drop trigger if exists shift_schedules_sync on crm.shift_schedules;
create trigger shift_schedules_sync after insert or update or delete or truncate on crm.shift_schedules
  for each statement execute function crm.bump_sync_version();
drop trigger if exists attendance_corrections_sync on crm.attendance_corrections;
create trigger attendance_corrections_sync after insert or update or delete or truncate on crm.attendance_corrections
  for each statement execute function crm.bump_sync_version();
drop trigger if exists wfh_requests_sync on crm.wfh_requests;
create trigger wfh_requests_sync after insert or update or delete or truncate on crm.wfh_requests
  for each statement execute function crm.bump_sync_version();
drop trigger if exists leave_requests_sync on crm.leave_requests;
create trigger leave_requests_sync after insert or update or delete or truncate on crm.leave_requests
  for each statement execute function crm.bump_sync_version();
drop trigger if exists leave_balances_sync on crm.leave_balances;
create trigger leave_balances_sync after insert or update or delete or truncate on crm.leave_balances
  for each statement execute function crm.bump_sync_version();
drop trigger if exists leave_policies_sync on crm.leave_policies;
create trigger leave_policies_sync after insert or update or delete or truncate on crm.leave_policies
  for each statement execute function crm.bump_sync_version();
drop trigger if exists holidays_sync on crm.holidays;
create trigger holidays_sync after insert or update or delete or truncate on crm.holidays
  for each statement execute function crm.bump_sync_version();
drop trigger if exists payroll_records_sync on crm.payroll_records;
create trigger payroll_records_sync after insert or update or delete or truncate on crm.payroll_records
  for each statement execute function crm.bump_sync_version();
drop trigger if exists performance_reviews_sync on crm.performance_reviews;
create trigger performance_reviews_sync after insert or update or delete or truncate on crm.performance_reviews
  for each statement execute function crm.bump_sync_version();
drop trigger if exists review_cycles_sync on crm.review_cycles;
create trigger review_cycles_sync after insert or update or delete or truncate on crm.review_cycles
  for each statement execute function crm.bump_sync_version();
drop trigger if exists goals_okrs_sync on crm.goals_okrs;
create trigger goals_okrs_sync after insert or update or delete or truncate on crm.goals_okrs
  for each statement execute function crm.bump_sync_version();
drop trigger if exists training_programs_sync on crm.training_programs;
create trigger training_programs_sync after insert or update or delete or truncate on crm.training_programs
  for each statement execute function crm.bump_sync_version();
drop trigger if exists employee_benefits_sync on crm.employee_benefits;
create trigger employee_benefits_sync after insert or update or delete or truncate on crm.employee_benefits
  for each statement execute function crm.bump_sync_version();
drop trigger if exists benefit_enrollments_sync on crm.benefit_enrollments;
create trigger benefit_enrollments_sync after insert or update or delete or truncate on crm.benefit_enrollments
  for each statement execute function crm.bump_sync_version();
drop trigger if exists tax_declarations_sync on crm.tax_declarations;
create trigger tax_declarations_sync after insert or update or delete or truncate on crm.tax_declarations
  for each statement execute function crm.bump_sync_version();
drop trigger if exists hr_policies_sync on crm.hr_policies;
create trigger hr_policies_sync after insert or update or delete or truncate on crm.hr_policies
  for each statement execute function crm.bump_sync_version();
drop trigger if exists policy_acknowledgements_sync on crm.policy_acknowledgements;
create trigger policy_acknowledgements_sync after insert or update or delete or truncate on crm.policy_acknowledgements
  for each statement execute function crm.bump_sync_version();
drop trigger if exists finance_settings_sync on crm.finance_settings;
create trigger finance_settings_sync after insert or update or delete or truncate on crm.finance_settings
  for each statement execute function crm.bump_sync_version();
drop trigger if exists invoices_sync on crm.invoices;
create trigger invoices_sync after insert or update or delete or truncate on crm.invoices
  for each statement execute function crm.bump_sync_version();
drop trigger if exists receipts_sync on crm.receipts;
create trigger receipts_sync after insert or update or delete or truncate on crm.receipts
  for each statement execute function crm.bump_sync_version();
drop trigger if exists recurring_invoices_sync on crm.recurring_invoices;
create trigger recurring_invoices_sync after insert or update or delete or truncate on crm.recurring_invoices
  for each statement execute function crm.bump_sync_version();
drop trigger if exists expenses_sync on crm.expenses;
create trigger expenses_sync after insert or update or delete or truncate on crm.expenses
  for each statement execute function crm.bump_sync_version();
drop trigger if exists vendors_sync on crm.vendors;
create trigger vendors_sync after insert or update or delete or truncate on crm.vendors
  for each statement execute function crm.bump_sync_version();
drop trigger if exists vendor_bills_sync on crm.vendor_bills;
create trigger vendor_bills_sync after insert or update or delete or truncate on crm.vendor_bills
  for each statement execute function crm.bump_sync_version();
drop trigger if exists contract_assignments_sync on crm.contract_assignments;
create trigger contract_assignments_sync after insert or update or delete or truncate on crm.contract_assignments
  for each statement execute function crm.bump_sync_version();
drop trigger if exists timesheets_sync on crm.timesheets;
create trigger timesheets_sync after insert or update or delete or truncate on crm.timesheets
  for each statement execute function crm.bump_sync_version();
drop trigger if exists fnf_payments_sync on crm.fnf_payments;
create trigger fnf_payments_sync after insert or update or delete or truncate on crm.fnf_payments
  for each statement execute function crm.bump_sync_version();
drop trigger if exists bank_statement_lines_sync on crm.bank_statement_lines;
create trigger bank_statement_lines_sync after insert or update or delete or truncate on crm.bank_statement_lines
  for each statement execute function crm.bump_sync_version();
drop trigger if exists manual_journals_sync on crm.manual_journals;
create trigger manual_journals_sync after insert or update or delete or truncate on crm.manual_journals
  for each statement execute function crm.bump_sync_version();
drop trigger if exists budgets_sync on crm.budgets;
create trigger budgets_sync after insert or update or delete or truncate on crm.budgets
  for each statement execute function crm.bump_sync_version();
drop trigger if exists tasks_sync on crm.tasks;
create trigger tasks_sync after insert or update or delete or truncate on crm.tasks
  for each statement execute function crm.bump_sync_version();
drop trigger if exists announcements_sync on crm.announcements;
create trigger announcements_sync after insert or update or delete or truncate on crm.announcements
  for each statement execute function crm.bump_sync_version();
drop trigger if exists notifications_sync on crm.notifications;
create trigger notifications_sync after insert or update or delete or truncate on crm.notifications
  for each statement execute function crm.bump_sync_version();
drop trigger if exists approval_requests_sync on crm.approval_requests;
create trigger approval_requests_sync after insert or update or delete or truncate on crm.approval_requests
  for each statement execute function crm.bump_sync_version();
drop trigger if exists audit_logs_sync on crm.audit_logs;
create trigger audit_logs_sync after insert or update or delete or truncate on crm.audit_logs
  for each statement execute function crm.bump_sync_version();
drop trigger if exists compliance_items_sync on crm.compliance_items;
create trigger compliance_items_sync after insert or update or delete or truncate on crm.compliance_items
  for each statement execute function crm.bump_sync_version();
drop trigger if exists data_quality_issues_sync on crm.data_quality_issues;
create trigger data_quality_issues_sync after insert or update or delete or truncate on crm.data_quality_issues
  for each statement execute function crm.bump_sync_version();
drop trigger if exists integration_services_sync on crm.integration_services;
create trigger integration_services_sync after insert or update or delete or truncate on crm.integration_services
  for each statement execute function crm.bump_sync_version();
drop trigger if exists workflow_rules_sync on crm.workflow_rules;
create trigger workflow_rules_sync after insert or update or delete or truncate on crm.workflow_rules
  for each statement execute function crm.bump_sync_version();
drop trigger if exists email_outbox_sync on crm.email_outbox;
create trigger email_outbox_sync after insert or update or delete or truncate on crm.email_outbox
  for each statement execute function crm.bump_sync_version();
drop trigger if exists stored_files_sync on crm.stored_files;
create trigger stored_files_sync after insert or update or delete or truncate on crm.stored_files
  for each statement execute function crm.bump_sync_version();

-- Lock the schema down: no access through the public API keys
alter table crm.organizations enable row level security;
alter table crm.users enable row level security;
alter table crm.organization_settings enable row level security;
alter table crm.clients enable row level security;
alter table crm.client_leads enable row level security;
alter table crm.client_communications enable row level security;
alter table crm.jobs enable row level security;
alter table crm.candidates enable row level security;
alter table crm.applications enable row level security;
alter table crm.interviews enable row level security;
alter table crm.placements enable row level security;
alter table crm.message_templates enable row level security;
alter table crm.recruiter_targets enable row level security;
alter table crm.agent_profiles enable row level security;
alter table crm.referrals enable row level security;
alter table crm.referral_messages enable row level security;
alter table crm.commission_ledger enable row level security;
alter table crm.payouts enable row level security;
alter table crm.payee_profiles enable row level security;
alter table crm.employees enable row level security;
alter table crm.onboarding_records enable row level security;
alter table crm.employee_documents enable row level security;
alter table crm.employee_assets enable row level security;
alter table crm.probation_records enable row level security;
alter table crm.promotion_records enable row level security;
alter table crm.transfer_records enable row level security;
alter table crm.salary_revisions enable row level security;
alter table crm.exit_records enable row level security;
alter table crm.employee_requests enable row level security;
alter table crm.attendance_records enable row level security;
alter table crm.shift_schedules enable row level security;
alter table crm.attendance_corrections enable row level security;
alter table crm.wfh_requests enable row level security;
alter table crm.leave_requests enable row level security;
alter table crm.leave_balances enable row level security;
alter table crm.leave_policies enable row level security;
alter table crm.holidays enable row level security;
alter table crm.payroll_records enable row level security;
alter table crm.performance_reviews enable row level security;
alter table crm.review_cycles enable row level security;
alter table crm.goals_okrs enable row level security;
alter table crm.training_programs enable row level security;
alter table crm.employee_benefits enable row level security;
alter table crm.benefit_enrollments enable row level security;
alter table crm.tax_declarations enable row level security;
alter table crm.hr_policies enable row level security;
alter table crm.policy_acknowledgements enable row level security;
alter table crm.finance_settings enable row level security;
alter table crm.invoices enable row level security;
alter table crm.receipts enable row level security;
alter table crm.recurring_invoices enable row level security;
alter table crm.expenses enable row level security;
alter table crm.vendors enable row level security;
alter table crm.vendor_bills enable row level security;
alter table crm.contract_assignments enable row level security;
alter table crm.timesheets enable row level security;
alter table crm.fnf_payments enable row level security;
alter table crm.bank_statement_lines enable row level security;
alter table crm.manual_journals enable row level security;
alter table crm.budgets enable row level security;
alter table crm.tasks enable row level security;
alter table crm.announcements enable row level security;
alter table crm.notifications enable row level security;
alter table crm.approval_requests enable row level security;
alter table crm.audit_logs enable row level security;
alter table crm.compliance_items enable row level security;
alter table crm.data_quality_issues enable row level security;
alter table crm.integration_services enable row level security;
alter table crm.workflow_rules enable row level security;
alter table crm.email_outbox enable row level security;
alter table crm.stored_files enable row level security;
alter table crm._sync_state enable row level security;
revoke all on schema crm from anon, authenticated;
revoke all on all tables in schema crm from anon, authenticated;
